### ISSUE TITLE
Unable to launch nvidia-ctk

### ISSUE THREAD

**Issue by gab9281** [NVIDIA/nvidia-container-toolkit#101]
I just found out that all my container needing hardware accelleration are stopped.
Here's the error i have from a hook i created to refresh CDI on nvidia driver update.
I cannot even start nvidia-ctk.

command : `nvidia-ctk`

Error : `nvidia-ctk: error while loading shared libraries: unexpected PLT reloc type 0x00`

Libraries : 
libnvidia-container 1.13.5-1
libnvidia-container-tools 1.13.5-1
nvidia 535.98-4
nvidia-container-toolkit 1.13.5-1
nvidia-utils 535.98-1
opencl-nvidia 535.98-1
cuda 12.2.0-1

**Comment by elezar** [comment]
@gab9281 was this working before? If so, which version? What is your operating system?

If you're using Arch this could be related to https://gitlab.com/nvidia/container-toolkit/container-toolkit/-/issues/17

**Comment by gab9281** [comment]
Yes it was and yes I am , thanks to refer me to the other ticket.
