### ISSUE TITLE
rootless docker and nvidia gpus not working anymore with v1.14.0

### ISSUE THREAD

**Issue by dnns92** [NVIDIA/nvidia-container-toolkit#106]
Ever since the last upgrade I cannot run docker containers with gpu support anymore in rootless mode.
I have set `no-croups=true`, and also tried to set it to `no-cgroups=false`. 
Upon `docker run --rm --runtime=nvidia --gpus all nvidia/cuda:11.6.2-base-ubuntu20.04 nvidia-smi` I receive this error message:
~~~text
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: mount error: failed to add device rules: unable to find any existing device filters attached to the cgroup: bpf_prog_query(BPF_CGROUP_DEVICE) failed: operation not permitted: unknown.
~~~

System Information
~~~text
Ubuntu 22.04, kernel: Linux 5.15.0-82-generic 
Tested on RTX 3060, 3090, TITAN RTX (all different machines, 1 GPU per machine)
AMD and Intel CPU tested

nvidia-container-cli -V
cli-version: 1.14.0
lib-version: 1.14.0
build date: 2023-08-29T15:25+00:00
build revision: 6a24508dff6cb36841114ff4c1287cd29ded72af
build compiler: x86_64-linux-gnu-gcc-7 7.5.0
build platform: x86_64
~~~

We use rootless docker, this is my `/etc/nvidia-container-runtime/config.toml`:
~~~bash
#accept-nvidia-visible-devices-as-volume-mounts = false
#accept-nvidia-visible-devices-envvar-when-unprivileged = true
disable-require = false
#swarm-resource = "DOCKER_RESOURCE_GPU"

[nvidia-container-cli]
#debug = "/var/log/nvidia-container-toolkit.log"
environment = []
#ldcache = "/etc/ld.so.cache"
ldconfig = "@/sbin/ldconfig.real"
load-kmods = true
no-cgroups = true
#path = "/usr/bin/nvidia-container-cli"
#root = "/run/nvidia/driver"
#user = "root:video"

[nvidia-container-runtime]
#debug = "/var/log/nvidia-container-runtime.log"
log-level = "info"
mode = "auto"
runtimes = ["docker-runc", "runc"]

[nvidia-container-runtime.modes]

[nvidia-container-runtime.modes.csv]
mount-spec-path = "/etc/nvidia-container-runtime/host-files-for-container.d"
~~~

**Comment by dnns92** [comment]
I did manage to find a temporary workaround: Downgrading to `nvidia-container-toolkit 1.13.5-1`. Btw, we also use high subuids in our rootless setup. Maybe it's related. Nevertheless, I think someone at nvidia should have a look into this.

**Comment by elezar** [comment]
@dnns92 there was a refactoring of the handling of config files that may have caused a regression. Could you configure:
```
[nvidia-container-cli]
debug = "/some/world/writable/path/file.log"
```
and include the log file generated when running a container?

**Comment by elezar** [comment]
@dnns92 I have found the issue locally. Would you be able to test a custom build off the top of the tree, or would you wait for a patch release?

**Comment by dnns92** [comment]
Hey elezar, thank you for your fast action! I think I'll wait for a patch release.
Cheers, and again thank you!

**Comment by elezar** [comment]
@dnns92 the 1.14.1 release has been published to our public repositories. It will also be scheduled to be published to the CUDA Download Repositories, but that will happen at today 16:00 UTC at the earliest.
