### ISSUE TITLE
nvidia-container-cli unknown device since container toolkit upgrade to 1.14

### ISSUE THREAD

**Issue by dcarrion87** [NVIDIA/nvidia-container-toolkit#108]
Starting receiving this error after recent update on g4dn AWS instances. Trying to work back from where it all went wrong at the moment.

K3S logs:

> Sep 08 08:58:07 REDACTED k3s[8174]:         nvidia-container-cli: device error: /var/run/nvidia-container-devices: unknown device: unknown
Sep 08 08:58:07 REDACTED k3s[8174]:         rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container >
Sep 08 08:58:07 REDACTED k3s[8174]: E0908 08:58:07.521280    8174 remote_runtime.go:474] "StartContainer from runtime service failed" err=

nvidia-smi:

```
# nvidia-smi
Fri Sep  8 09:04:42 2023
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.54.03              Driver Version: 535.54.03    CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:1E.0 Off |                    0 |
| N/A   32C    P8               9W /  70W |      2MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
```

Packages:

```
ii  libnvidia-cfg1-535-server:amd64      535.54.03-0ubuntu0.22.04.1              amd64        NVIDIA binary OpenGL/GLX configuration library
ii  libnvidia-common-535-server          535.54.03-0ubuntu0.22.04.1              all          Shared files used by the NVIDIA libraries
ii  libnvidia-compute-535-server:amd64   535.54.03-0ubuntu0.22.04.1              amd64        NVIDIA libcompute package
ii  libnvidia-container-tools            1.14.0-1                                amd64        NVIDIA container runtime library (command-line tools)
ii  libnvidia-container1:amd64           1.14.0-1                                amd64        NVIDIA container runtime library
ii  libnvidia-decode-535-server:amd64    535.54.03-0ubuntu0.22.04.1              amd64        NVIDIA Video Decoding runtime libraries
ii  libnvidia-encode-535-server:amd64    535.54.03-0ubuntu0.22.04.1              amd64        NVENC Video Encoding runtime library
ii  libnvidia-extra-535-server:amd64     535.54.03-0ubuntu0.22.04.1              amd64        Extra libraries for the NVIDIA Server Driver
ii  libnvidia-fbc1-535-server:amd64      535.54.03-0ubuntu0.22.04.1              amd64        NVIDIA OpenGL-based Framebuffer Capture runtime library
ii  libnvidia-gl-535-server:amd64        535.54.03-0ubuntu0.22.04.1              amd64        NVIDIA OpenGL/GLX/EGL/GLES GLVND libraries and Vulkan ICD
ii  nvidia-compute-utils-535-server      535.54.03-0ubuntu0.22.04.1              amd64        NVIDIA compute utilities
ii  nvidia-container-toolkit             1.14.0-1                                amd64        NVIDIA Container toolkit
ii  nvidia-container-toolkit-base        1.14.0-1                                amd64        NVIDIA Container Toolkit Base
ii  nvidia-dkms-535-server               535.54.03-0ubuntu0.22.04.1              amd64        NVIDIA DKMS package
ii  nvidia-driver-535-server             535.54.03-0ubuntu0.22.04.1              amd64        NVIDIA Server Driver metapackage
ii  nvidia-firmware-535-server-535.54.03 535.54.03-0ubuntu0.22.04.1              amd64        Firmware files used by the kernel module
ii  nvidia-kernel-common-535-server      535.54.03-0ubuntu0.22.04.1              amd64        Shared files used with the kernel module
ii  nvidia-kernel-source-535-server      535.54.03-0ubuntu0.22.04.1              amd64        NVIDIA kernel source package
ii  nvidia-utils-535-server              535.54.03-0ubuntu0.22.04.1              amd64        NVIDIA Server Driver support binaries
ii  xserver-xorg-video-nvidia-535-server 535.54.03-0ubuntu0.22.04.1              amd64        NVIDIA binary Xorg driver
```

**Comment by dcarrion87** [comment]
Downgrading to 1.13.5-1 fixes this. We'll be pinning to that version for now until we understand more.

**Comment by elezar** [comment]
@dcarrion87 are you using the driver container or applying any specific configs to the `/etc/nvidia-container-runtime/config.toml` file?

There is a known issue with reading this file from the `nvidia-container-runtime-hook` that is invoked when a container requests a device. One workaround would be to put the file in `/run/driver/nvidia/etc/nvidia-container-runtime/config.toml` instead. In theory a symlink from `/run/driver/nvidia/etc/nvidia-container-runtime/config.toml` => `/etc/nvidia-container-runtime/config.toml` should also work.

**Comment by elezar** [comment]
See #106 for another manifestation of this bug.

**Comment by dcarrion87** [comment]
@elezar that's us. How permanent is that? E.g. Can I hold off for 2 weeks and expect an update that's likely to fix this without us doing anything more?

**Comment by elezar** [comment]
> @elezar that's us. How permanent is that? E.g. Can I hold off for 2 weeks and expect an update that's likely to fix this without us doing anything more? We have a few variation of systems on different versions so want to keep consistent and permanent fix.

I am working on pushing out a patch release today that *should* address the bug. The workaround should continue to function even after the fix has been applied -- although it may lead to confusion if multiple config files are present on the system.

**Comment by elezar** [comment]
@dcarrion87 the 1.14.1 release has been published to our public repositories. It will also be scheduled to be published to the CUDA Download Repositories, but that will happen at today 16:00 UTC at the earliest.

**Comment by dcarrion87** [comment]
@elezar thanks for the speedy resolve. The AMIs have reverted to the older version but I'll look to rebuild new one when it lands in the CUDA repos.

**Comment by dcarrion87** [comment]
Looks like these ones haven't been updated as of yet: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/

**Comment by dcarrion87** [comment]
@elezar just a courtesy note to let you know it dropped into the repo and I have tested today and it's working well 👍

**Comment by elezar** [comment]
@dcarrion87 thanks for the confirmation. Do you mind if we close this issue then?
