### ISSUE TITLE
Support for openSUSE Tumbleweed

### ISSUE THREAD

**Issue by kilian-hu** [NVIDIA/nvidia-container-toolkit#110]
Hi,

I'm using openSUSE Tumbleweed and tried to follow the [installation guide with zypper](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#installing-with-zypper) but encountered this error: `Problem: nothing provides 'libseccomp' needed by the to be installed nvidia-container-toolkit-1.14.1-1.x86_64`.

I found that in openSUSE Tumbleweed the package is actually called `libseccomp2`. Would it be possible to adjust the repo such that the installation on openSUSE Tumbleweed works? Any help is highly appreciated :)

**Comment by pmrj33** [comment]
Wish I could provide some help but I am suffering from the same problem. Wish I could tell zypper to replace the dependency libseccomp2 by libseccomp since it is what provides the package libseccomp 

Have a great day! And thank you!

**Comment by elezar** [comment]
@kilian-hu @pmrj33 would creating a dummy `libseccomp` package with somethign like `fpm` be an option. We use this to test our packages that have a dependency on `docker` without actually installing `docker` explicitly.

For example: https://github.com/NVIDIA/nvidia-container-toolkit/blob/6094effd58d88becdfb7900ef5df7fa274686620/test/release/docker/centos8/Dockerfile#L13-L25

**Comment by pmrj33** [comment]
I ended up building the package nvidia-container-toolkit (repo) from github with target opensuse-leap15.1-x86_64 and creating a local repo for nvidia-container-toolkit to install on the system and to zypper to handle. 

I only just installed and didn't yield any errors. Also run on podman this simple example `podman run --rm --device nvidia.com/gpu=all --security-opt=label=disable ubuntu nvidia-smi` and it executed perfectly.

**Comment by elezar** [comment]
@pmrj33 note that only the `libnvidia-container*` packages have a `libseccomp` dependency, so it should only be required to build these from source.

Another note: If you're only looking to use CDI (which your example suggests), then only the `nvidia-container-toolkit-base` package is required. This should have no dependency on `libnvidia-container-tools` and would remove the need to build things from source.

**Comment by pmrj33** [comment]
Alright, very good point. I am kind of learning how to use podman/docker + nvidia and the exact terms definition. Indeed I see I bypassed the problem with an extreme solution. But when it was building the packages I noticed it fetched libseccomp2 instead of libseccomp, that why I got away with it.

Again thank you for your help.  And I had done the build before read your post @elezar and thank you for the solution

**Comment by msamsu** [comment]
> I ended up building the package nvidia-container-toolkit (repo) from github with target opensuse-leap15.1-x86_64 and creating a local repo for nvidia-container-toolkit to install on the system and to zypper to handle.
> 

Hi @pmrj33 , could you provide the list of commands for this workabout?

**Comment by msamsu** [comment]
Isn't there any other way how to work around this quickly? Can we e.g. install libseccomp on Tumbleweed manually? Or can we downgrade Tumbleweed to previously working version?

**Comment by kilian-hu** [comment]
Thank you very much for the help @elezar :)
Installing a dummy `libseccomp` package built by fpm did the trick.
It works now, so feel free to close the issue.

**Comment by benjaminsabatini** [comment]
This seems un-fixed. Is there a solution other than installing a dummy package?

**Comment by elezar** [comment]
Hi all. I am working on a solution that involves adding a virtual package that provides `libseccomp.so` while depending on `libseccomp2`. This would mean that an additional package would need to be installed on SUSE systems, but would not require a dummy package.

Would this be workable?

**Comment by rajinder-yadav** [comment]
@elezar any idea when your solution will be available?

**Comment by bubbleguuum** [comment]
I found out that when installing package 'nvidia-container-toolkit' you can ignore the error that `libseccomp` and force install.

Only `/usr/lib64/libnvidia-container.so.1` (in package `libnvidia-container1) and `/usr/bin/nvidia-container-cli` (package `libnvidia-container-tools`) depend on libseccomp and they findsit just fine:
```
 ldd /usr/lib64/libnvidia-container.so.1
        ...
	libseccomp.so.2 => /lib64/libseccomp.so.2 (0x00007f5f4b998000)
	...
```

Speaking of which , one has to wonder why that `libseccomp` dependency is on package  'nvidia-container-toolkit' rather than the 2 other mentioned packages that have binaries depending on it.

However once I got 'nvidia-container-toolkit' force installed, I add to modify `/etc/nvidia-container-runtime/config.toml` to add a `user = "root:video` line, for `docker run --rm --runtime=nvidia --gpus all ubuntu nvidia-smi` to not fail with (note: using `sudo` does not help):

```
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: initialization error: nvml error: insufficient permissions: unknown.
```

**Comment by elezar** [comment]
@bubbleguuum thanks for your latest reply. With regards to:
> Speaking of which, one has to wonder why that libseccomp dependency is on package nvidia-container-toolkit rather than the 2 other mentioned packages that have actual binaries depending on libseccomp.

This is unexpected. I assume that this is a legacy change that has made it into this package and was never an issue until we started rolling out our "unified" packages. I think we can definitely drop the `libseccomp` dependency entirely for the `nvidia-container-toolkit` package. I will be sure to include that in the upcoming release.

With regards to:
> I add to modify /etc/nvidia-container-runtime/config.toml to add a user = "root:video line, for docker run --rm --runtime=nvidia --gpus all ubuntu nvidia-smi to not fail with (note: using sudo does not help):

What does:
```
nvidia-ctk config
```
output on your system?

**Comment by elezar** [comment]
@rajinder-yadav if we can get consensus that this is a reasonable workaround (as opposed to force-installing the `libnvidia-container*` packages), then it would be included in the upcoming v1.15.0 release.

**Comment by bubbleguuum** [comment]
@elezar 

Default output of `nvidia-ctk config` (after package installation):

```
#accept-nvidia-visible-devices-as-volume-mounts = false
#accept-nvidia-visible-devices-envvar-when-unprivileged = true
disable-require = false
supported-driver-capabilities = "compat32,compute,display,graphics,ngx,utility,video"
#swarm-resource = "DOCKER_RESOURCE_GPU"

[nvidia-container-cli]
#debug = "/var/log/nvidia-container-toolkit.log"
environment = []
#ldcache = "/etc/ld.so.cache"
ldconfig = "@/sbin/ldconfig"
load-kmods = true
#no-cgroups = false
#path = "/usr/bin/nvidia-container-cli"
#root = "/run/nvidia/driver"

[nvidia-container-runtime]
#debug = "/var/log/nvidia-container-runtime.log"
log-level = "info"
mode = "auto"
runtimes = ["docker-runc", "runc"]

[nvidia-container-runtime.modes]

[nvidia-container-runtime.modes.cdi]
annotation-prefixes = ["cdi.k8s.io/"]
default-kind = "nvidia.com/gpu"
spec-dirs = ["/etc/cdi", "/var/run/cdi"]

[nvidia-container-runtime.modes.csv]
mount-spec-path = "/etc/nvidia-container-runtime/host-files-for-container.d"

[nvidia-container-runtime-hook]
path = "nvidia-container-runtime-hook"
skip-mode-detection = false

[nvidia-ctk]
path = "nvidia-ctk"
```

Notice that there is no user line. If I open `/etc/nvidia-container-runtime/config.toml` I see a commented empty user line: `#user = ""`. As I mentioned, I have to add the line 'user = "root:video"` to fix that permission error.

**Comment by elezar** [comment]
Thanks for the feedback @bubbleguuum. The logic added to detect a SUSE-based system for the generation of the default config was not working correctly. I have created https://gitlab.com/nvidia/container-toolkit/container-toolkit/-/merge_requests/532 to address this.

**Comment by rajinder-yadav** [comment]
Hello I can confirm the fix made by @elezar is working, thank you. 🙏
I can now run ollam locally using docker container and it's blazing fast! ⚡
