### ISSUE TITLE
`sudo docker run --rm --runtime=nvidia --gpus all ubuntu nvidia-smi` failing `last insn is not an exit or jmp`

### ISSUE THREAD

**Issue by ecidon** [NVIDIA/nvidia-container-toolkit#117]
Hi I am following the installation guide with docker-ce here:
https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html

After running everything and restarting docker when I run:
```
sudo docker run --rm --runtime=nvidia --gpus all ubuntu nvidia-smi
```

I get the following error:
```
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: mount error: failed to add device rules: unable to generate new device filter program from existing programs: unable to create new device filters program: load program: invalid argument: last insn is not an exit or jmp
processed 0 insns (limit 1000000) max_states_per_insn 0 total_states 0 peak_states 0 mark_read 0: unknown.
```

I am running on Ubuntu 22.04
CUDA version is 12.2
Docker version 24.0.6
nvidia-container-toolkit version 1.14.2-1

**Comment by ecidon** [comment]
Hi can someone help me with this?

**Comment by angerson** [comment]
Looks similar to https://github.com/NVIDIA/libnvidia-container/issues/176. 

You may be able to fix this by reducing `bpf_jit_harden` from 2 to 1, e.g.:

```bash
sudo bash -c "echo net.core.bpf_jit_harden=1 > /etc/sysctl.d/91-nvidia-docker.conf"
sudo sysctl --system
sudo systemctl restart docker
```

**Comment by DimanNe** [comment]
Yep! It worked for me too.

It would be nice if you could add this instruction in the official documentation (https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html)

**Comment by klueska** [comment]
@mikemckiernan Can we add a note in the docs about this?
