### ISSUE TITLE
package cant build in nvidia container

### ISSUE THREAD

**Issue by an99990** [NVIDIA/nvidia-container-toolkit#13]
Hi, 
So I have noticed a recurrent issue with using nvidia-container.
I was trying to build AdelaitDET and mmsegmentation and those got the same error about not being able to find some torch library.
I will link the two issues here :

AdelaiDET issue : https://github.com/aim-uofa/AdelaiDet/issues/516
mmsegmentation : https://github.com/open-mmlab/mmcv/issues/1714

I believe these issues are caused by the container because when i build it outside it works.

Please let me know what I can do to fix.
Thank you

**Comment by elezar** [comment]
Hi @an99990. From you description, this would seem to be an issue with the container you are building the application in. You don't mention which container image you are using in either of the linked issues. Please ensure that you are using an image with the required development libraries installed.

**Comment by an99990** [comment]
hi @elezar thank you for your answer,
I am relatively new with docker. I have tried to look into the documentation of nvidia container but havent found much.
`docker run --gpus all -it --ipc=host --ulimit memlock=-1 --ulimit stack=67108864 --rm -v $(pwd):/opt/bord -w /opt/bord nvcr.io/nvidia/pytorch:22.01-py3
`

Please let me know, if i should change docker or anything

**Comment by ArangoGutierrez** [comment]
I am closing this issue. If any problems persist using the latest version of the NVIDIA Container Toolkit, please open a new issue.
