### ISSUE TITLE
Repository Gives 503 error

### ISSUE THREAD

**Issue by iammyownalterego** [NVIDIA/nvidia-container-toolkit#144]
I followed the instructions to setup the .repo file on my RHEL 7.9 server 
[https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html](url)
to attempt to install libnvidia-container, but It seems there's nothing behind the url when I attempt to perform a "yum info". I even noted the older documentation and tested substituting "centos7" and "centos7.9" in the baseurl value in the .repo file to no avail. I'm testing on a sandboxed environment and need the rpm(s) so I can copy them to cd and move them manually.

**Comment by elezar** [comment]
Could you confirm the contents of your downloaded repo file?

Just to confirm, you're using the `https://nvidia.github.io/libnvidia-container/stable/rpm/nvidia-container-toolkit.repo` URL?

**Comment by iammyownalterego** [comment]
My apologies for the late reply, but yes. I double-checked the downloaded
file.

**Comment by elezar** [comment]
I have just followed the following instructions on a clean `centos:7` and `registry.access.redhat.com/rhel7:7.9-1197` image(s):
```
$ curl -s -L https://nvidia.github.io/libnvidia-container/stable/rpm/nvidia-container-toolkit.repo | tee /etc/yum.repos.d/nvidia-container-toolkit.repo
```
followed by:
```
$ yum info nvidia-container-toolkit
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
 * base: ftpmirror.your.org
 * extras: mirror.siena.edu
 * updates: mirrors.tripadvisor.com
Installed Packages
Name        : nvidia-container-toolkit
Arch        : x86_64
Version     : 1.14.3
Release     : 1
Size        : 2.6 M
Repo        : installed
From repo   : nvidia-container-toolkit
Summary     : NVIDIA Container Toolkit
URL         : https://github.com/NVIDIA/nvidia-container-toolkit
License     : Apache-2.0
Description : Provides tools and utilities to enable GPU support in containers.
```
(where this is the output in `centos:7`, but the RHEL image also works)

Which commands are you running and what errors are triggered?

**Comment by iammyownalterego** [comment]
My apologies, it works fine now. I had to speak with site network security
and IA folks and although everything was briefed(promised) to be open, I
helped them to discover some "security measures" 🙃 in place that were
blocking access.

It's working fine now. I thank you for your time and support--and again, I
apologize for the time lost looking into this for me.

You've been a great help!
