### ISSUE TITLE
Nvidia-container-toolkit Podman. Error: error setting up CDI devices: unresolvable CDI devices nvidia.com/gpu=all 

### ISSUE THREAD

**Issue by irudkin** [NVIDIA/nvidia-container-toolkit#146]
I am continually getting the error Error: error setting up CDI devices: unresolvable CDI devices [nvidia.com/gpu=all](http://nvidia.com/gpu=all).
Environment:

Unbuntu 22.04
Podman version 4.4.1
NVIDIA Driver Driver Version: 535.129.03 CUDA Version: 12.2
NVIDIA Container Toolkit CLI version 1.14.3
I have followed these instructions [here](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/cdi-support.html).
I have checked or did the following:
1. sudo apt-get install -y nvidia-container-toolkit
Reading package lists… Done
Building dependency tree… Done
Reading state information… Done
nvidia-container-toolkit is already the newest version (1.14.3-1).

2. nvidia-smi -L
GPU 0: NVIDIA GeForce RTX 2060 (UUID: GPU-2f68f999-7b41-e64a-3709-0c8c4fa756c0)

3. nvidia-ctk --version
NVIDIA Container Toolkit CLI version 1.14.3
commit: 53b24618a542025b108239fe602e66e912b7d6e2

4. sudo nvidia-ctk cdi list
INFO[0000] Found 2 CDI devices
[nvidia.com/gpu=0](http://nvidia.com/gpu=0)
[nvidia.com/gpu=all](http://nvidia.com/gpu=all)

5. sudo nvidia-ctk cdi generate --output=/var/run/cdi/nvidia.yaml and sudo nvidia-ctk cdi generate --output=/etc/cdi/nvidia.yaml followed by sudo chmod a+r /var/run/cdi/nvidia.yaml and sudo chmod a+r /etc/cdi/nvidia.yaml

6. Check user groups, they are: adm cdrom sudo dip video plugdev kvm render lpadmin lxd sambashare vtune

Note: The above points are not in order.

Yet running the command: sudo podman run --rm --device=[nvidia.com/gpu=all](http://nvidia.com/gpu=all) --security-opt=label=disable ubuntu nvidia-smi -L or podman run --rm --device [nvidia.com/gpu=all](http://nvidia.com/gpu=all) --security-opt=label=disable ubuntu nvidia-smi -L, results int the error:
Error: error setting up CDI devices: unresolvable CDI devices [nvidia.com/gpu=all](http://nvidia.com/gpu=all)

Any advice on how to get past this error would be gratefully received. Thank you.

**Comment by elezar** [comment]
The issue here may be that the CDI spec version being generated is too high for podman to load. Running `podman --debug` should output more information on errors that are triggered when initialising the CDI library.

Please also confirm that the `nvidia-ctk cdi generate` command is generating a `v0.5.0` specification in this case.

**Comment by irudkin** [comment]
Thank you. I did the following: 
sudo podman run --log-level debug --rm --device=nvidia.com/gpu=all --security-opt=label=disable ubuntu nvidia-smi -L

The following errors were triggered when creating the CDI registry: map[/etc/cdi/nvidia.yaml:[failed to load CDI Spec: invalid CDI Spec: invalid version "0.5.0"] /var/run/cdi/nvidia.yaml:[failed to load CDI Spec: invalid CDI Spec: invalid version "0.5.0"]] 

Which version of podman do you advise? Due to a bug in Ubuntu 22.-4 Apt install only installs Podman v3.4.4. I got v4.4.1 from here https://github.com/liebig/podman/releases (which I understand is not the latest).

**Comment by irudkin** [comment]
Thank you. Now following through with other issues with Podman resulting from trying to get an installation of Podman greater than v4.4.1 installed.

**Comment by elezar** [comment]
You can also add the --device-name-strategy=type-index flag to the cdi generate commands. This should generate a v0.3.0 spec.

**Comment by elezar** [comment]
Just a note. You seem to have `4.1.1` and not `4.4.1` installed. The latter *would* support spec version 0.5.0.
