### ISSUE TITLE
Building from source, undefined symbol: cuDriverGetVersion

### ISSUE THREAD

**Issue by oscarthorn** [NVIDIA/nvidia-container-toolkit#177]
Hi!
I'm trying to update to meta-tegra/yocto (embedded build system) recipe for this package. Currently it is using v1.9 which works fine. But building never versions produces:
`/usr/bin/nvidia-container-runtime: symbol lookup error: /usr/bin/nvidia-container-runtime: undefined symbol: cuDriverGetVersion`
I have tracked this down to the `internal/cuda/cuda.go` file which needs this symbol.

Is there some special flags that are needed to build correctly. What we have now is basically just `go install ./cmd/...`, though the actual command has a bunch of flags to make it cross-compile etc.

Actual command:
```
aarch64-oe4t-linux-go install -linkshared -p 32 -v -ldflags=-r /usr/lib/go/pkg/linux_arm64_dynlink   -extldflags ' -march=armv8-a+crc -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/home/dev/source/build/tmp/work/armv8a_tegra-oe4t-linux/nvidia-container-toolkit/1.9.0-r0/recipe-sysroot -Wl,-rpath-link=/home/dev/source/build/tmp/work/armv8a_tegra-oe4t-linux/nvidia-container-toolkit/1.9.0-r0/recipe-sysroot/usr/lib/go/pkg/linux_arm64_dynlink -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -fmacro-prefix-map=/home/dev/source/build/tmp/work/armv8a_tegra-oe4t-linux/nvidia-container-toolkit/1.9.0-r0=/usr/src/debug/nvidia-container-toolkit/1.9.0-r0                      -fdebug-prefix-map=/home/dev/source/build/tmp/work/armv8a_tegra-oe4t-linux/nvidia-container-toolkit/1.9.0-r0=/usr/src/debug/nvidia-container-toolkit/1.9.0-r0                      -fdebug-prefix-map=/home/dev/source/build/tmp/work/armv8a_tegra-oe4t-linux/nvidia-container-toolkit/1.9.0-r0/recipe-sysroot=                      -fdebug-prefix-map=/home/dev/source/build/tmp/work/armv8a_tegra-oe4t-linux/nvidia-container-toolkit/1.9.0-r0/recipe-sysroot-native=  -Wl,-z,relro,-z,now' -trimpath -modcacherw -buildmode=pie github.com/NVIDIA/nvidia-container-toolkit/cmd/nvidia-container-runtime github.com/NVIDIA/nvidia-container-toolkit/cmd/nvidia-container-runtime/modifier github.com/NVIDIA/nvidia-container-toolkit/cmd/nvidia-container-toolkit github.com/NVIDIA/nvidia-container-toolkit/cmd/nvidia-ctk github.com/NVIDIA/nvidia-container-toolkit/cmd/nvidia-ctk/hook github.com/NVIDIA/nvidia-container-toolkit/cmd/nvidia-ctk/hook/create-symlinks github.com/NVIDIA/nvidia-container-toolkit/cmd/nvidia-ctk/hook/update-ldcache
```
Sorry for the long command, I'm not sure what might be relevant.

I understand that this is hard for you to debug but any hints or thoughts are appreciated. 

I'm pretty sure that it is not an issue with libraries actually not being present as the cuda driver is present and replacing the binary we build with one from the deb repos makes it work.

**Comment by elezar** [comment]
We introduced bindings for some basic CUDA functions. It could be that the correct flags are not being applied to not have this be an issue when you run the executable.

In general, we use the following cgo flags:
```
#cgo LDFLAGS: -Wl,--unresolved-symbols=ignore-in-object-files
```
(and have had to add `-Wl,--export-dynamic` in newer go versions).

Not providing these have generally lead to the behaviour you mentioned -- although this is more commonly seen with the `go-nvml` bindings. See https://github.com/NVIDIA/go-nvml/issues/18 and https://github.com/NVIDIA/nvidia-container-toolkit/issues/49

**Comment by oscarthorn** [comment]
Thanks for the hint, got me thinking in the right direction. The issue was that `-z,now ` was enabled by default which did not play nice with the dynamic loading. Overriding it with `-z,lazy` when building fixed the problem.
