### ISSUE TITLE
nvidia-container-cli device error: unknown device

### ISSUE THREAD

**Issue by greenmoss** [NVIDIA/nvidia-container-toolkit#203]
Here is the invocation + error:
```
nvidia-container-cli --user configure --no-cgroups --ldconfig=@/usr/sbin/ldconfig.real --device=MIG-GPU-932bfb2c-849a-2a22-1e84-9eff6bc02b39/1/0 --compute --utility --require= --require= /var/snap/lxd/common/lxc/

nvidia-container-cli.real: device error: MIG-GPU-932bfb2c-849a-2a22-1e84-9eff6bc02b39/1/0: unknown device
```

This is from within an LXC container. On the OS I see that UUID, so presumably it's correct:
```
# nvidia-smi -L
GPU 0: NVIDIA A100 80GB PCIe (UUID: GPU-932bfb2c-849a-2a22-1e84-9eff6bc02b39)
  MIG 3g.40gb     Device  0: (UUID: MIG-0929581a-2be6-5dec-bf34-0954c6c529a6)
  MIG 3g.40gb     Device  1: (UUID: MIG-3adbed3a-d03d-549f-a016-ba1fd7359f23)
```

Environment:
* Ubuntu 20.04.6 LTS
* OS/.deb package nvidia-compute-utils-530 version 530.30.02-0ubuntu1
* OS/.deb package nvidia-container-toolkit 1.14.3-1
* OS/.deb package nvidia-mig-manager 0.5.4-1
* Ubuntu snap lxd 5.20-b670f1a
* Within snap, nvidia-container-cli 1.14.1

Any other information needed?

**Comment by elezar** [comment]
@greenmoss note that with newer driver versions the MIG devices have `MIG-` UUIDs and not `MIG-GPU-*/{{gid}}/{{cid}}` UUIDs. 

You should be able to refer to the `0/1` MIG device directly by running:
```
nvidia-container-cli --user configure --no-cgroups --ldconfig=@/usr/sbin/ldconfig.real --device=MIG-3adbed3a-d03d-549f-a016-ba1fd7359f23 --compute --utility --require= --require= /var/snap/lxd/common/lxc/
```

**Comment by greenmoss** [comment]
I tried it using the startup command you provided, and it works, thanks!

I'm going to see if there are any existing LXC bug reports on this, and if not I will open one.
