### ISSUE TITLE
ubi9 image for cuda 11.8

### ISSUE THREAD

**Issue by cdeepali** [NVIDIA/nvidia-container-toolkit#205]
Request to provide ubi9 images for cuda 11.8 on https://hub.docker.com/r/nvidia/cuda/

**Comment by y2k0999** [comment]
what does ubi mean as part of an image name?

**Comment by cdeepali** [comment]
It is for RHEL9 support.

**Comment by elezar** [comment]
The `nvidia/cuda` container images and the distributions they use are out of scope of the NVIDIA Container Toolkit.

Please create an issue against https://gitlab.com/nvidia/container-images/cuda instead.
