### ISSUE TITLE
How to submit a PR to docs? (Add instructions about Rootless Docker to `install-guide.html`)

### ISSUE THREAD

**Issue by AkihiroSuda** [NVIDIA/nvidia-container-toolkit#206]
I'd like to submit a PR to https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html about instructions about Rootless Docker, but I can't find the doc repo.

My PR will just have two sentences:
- To configure the container runtime with Rootless Docker, copy `/etc/docker/daemon.json` to `~/.config/docker/daemon.json`
- Open `/etc/nvidia-container-runtime`, and replace `#no-cgroups = false` to `no-cgroups = true`.

**Comment by elezar** [comment]
The source for the docs is available here: https://gitlab.com/nvidia/cloud-native/cnt-docs/-/tree/master/container-toolkit?ref_type=heads

Please submit a PR there and ping me for review.

**Comment by AkihiroSuda** [comment]
Thanks @elezar , submitted a merge request there:
- https://gitlab.com/nvidia/cloud-native/cnt-docs/-/merge_requests/373

**Comment by ArangoGutierrez** [comment]
https://gitlab.com/nvidia/cloud-native/cnt-docs/-/merge_requests/373 is merged
