### ISSUE TITLE
Amazon Linux 2023 - driver rpc error: failed to process request: unknown.

### ISSUE THREAD

**Issue by owu-1** [NVIDIA/nvidia-container-toolkit#208]
Trying to run a container using nvidia-container-toolkit fails with the error below when using Amazon Linux 2023.
```
[ssm-user@ip-10-0-0-73 ~]$ sudo docker run --rm --runtime=nvidia --gpus all ubuntu nvidia-smi
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: initialization error: driver rpc error: failed to process request: unknown.
[ssm-user@ip-10-0-0-73 ~]$ sudo docker run --rm --gpus all ubuntu nvidia-smi
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: initialization error: driver rpc error: failed to process request: unknown.
```
I am testing on an AWS g5g.xlarge instance running al2023-ami-2023.3.20240117.0-kernel-6.1-arm64 (ami-04c38c60b7d628f83). The software versions are nvidia-container-toolkit 1.14.3, nvidia driver 535.154.05, docker versions 24.0.5 and 25.0.0. The logs and scripts I used are attached below.
[docker-version-24.0.5.txt](https://github.com/NVIDIA/nvidia-container-toolkit/files/13995578/docker-version-24.0.5.txt)
[docker-version-24.0.5-script.txt](https://github.com/NVIDIA/nvidia-container-toolkit/files/13995579/docker-version-24.0.5-script.txt)
[docker-version-25.0.0.txt](https://github.com/NVIDIA/nvidia-container-toolkit/files/13995580/docker-version-25.0.0.txt)
[docker-version-25.0.0-script.txt](https://github.com/NVIDIA/nvidia-container-toolkit/files/13995581/docker-version-25.0.0-script.txt)

Running nvidia-container-toolkit 1.15.0~rc.1-1 with docker 25.0.0 has the same result.

**Comment by elezar** [comment]
@owu-1 could you please provide the output of the `nvidia-smi` command?

**Comment by owu-1** [comment]
The problem doesn't exist when using a g5g.2xlarge. I'll stick with Ubuntu since that's working. Thanks

**Comment by intergavg** [comment]
Was there any work done on fixing this for `g5g.xlarge` ? I am having the same issue,  these instance shape is the smallest, cheapest option on AWS, it is perfect shape to run cost effective workloads.
