### ISSUE TITLE
docker sees all GPUs despite access configured via Slurm (cgroups)

### ISSUE THREAD

**Issue by mil-ad** [NVIDIA/nvidia-container-toolkit#211]
We want to use nvidia-docker inside our slurm jobs. Inside the slurm job only the GPUs we have requested are visible when we look at `nvidia-smi` outputs. I was expecting if I do `docker run --gpus all nvidia-smi` I would also see the same number GPUs. However within the container nvidia-smi shows _all_ gpus available on that machine. The container seems to have the correct `CUDA_VISIBLE_DEVICES` environment variable but not the correct permissions.

Could it be related to the fact that by default docker needs sudo and we've created a user group so that we don't need sudo?

(BTW I noticed some things are different in Fedora but we're using Ubuntu.)

**Comment by klueska** [comment]
Closing for now as the originally posted issue seems to be resolved. @adamnovak feel free to open a separate issue for the feature request in your last comment.

**Comment by loopback-kr** [comment]
Try running podman with the --device=nvidia.com/gpu=all option.
