### ISSUE TITLE
Reinstalling Nvidia-Docker: Not able to run Nvidia Toolkit Containers (Jetson Nano - Jetpack 4.5.1)

### ISSUE THREAD

**Issue by kaisark** [NVIDIA/nvidia-container-toolkit#294]
[dpkg-nvidia.log](https://github.com/NVIDIA/nvidia-docker/files/6299643/dpkg-nvidia.log)
### 1. Issue or feature description
Reinstalling Nvidia-Docker not able to run Nvidia Toolkit Containers (Jetson Nano - Jetpack 4.5.1)

### 2. Steps to reproduce the issue
1. Remove Docker (sudo apt remove docker)
2. Remove nvidia-docker2 (sudo apt remove nvidia-docker2)
3. Reinstall Docker (https://docs.docker.com/engine/install/ubuntu/)
4. Reinstall nvidia-docker2 (https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#docker)
5. Run Nvidia Container (Arm64/aarch64) 
docker run --gpus all -it --rm --network host --volume ~/nvdli-data:/nvdli-nano/data --device /dev/video0 nvcr.io/nvidia/dli/dli-nano-ai:v2.0.1-r32.5.0

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [ ] Some nvidia-container information: `nvidia-container-cli -k -d /dev/tty info`
user@nano:~$ nvidia-container-cli -k -d /dev/tty info

-- WARNING, the following logs are for debugging purposes only --

I0412 19:56:22.542498 6496 nvc.c:372] initializing library context (version=1.3.3, build=bd9fc3f2b642345301cb2e23de07ec5386232317)
I0412 19:56:22.542617 6496 nvc.c:346] using root /
I0412 19:56:22.542633 6496 nvc.c:347] using ldcache /etc/ld.so.cache
I0412 19:56:22.542647 6496 nvc.c:348] using unprivileged user 1000:1000
I0412 19:56:22.542726 6496 nvc.c:389] attempting to load dxcore to see if we are running under Windows Subsystem for Linux (WSL)
I0412 19:56:22.543074 6496 nvc.c:391] dxcore initialization failed, continuing assuming a non-WSL environment
W0412 19:56:22.543425 6496 nvc.c:254] failed to detect NVIDIA devices
W0412 19:56:22.543857 6497 nvc.c:269] failed to set inheritable capabilities
W0412 19:56:22.543961 6497 nvc.c:270] skipping kernel modules load due to failure
I0412 19:56:22.544487 6498 driver.c:101] starting driver service
E0412 19:56:22.545001 6498 driver.c:161] could not start driver service: load library failed: libnvidia-ml.so.1: cannot open shared object file: no such file or directory
I0412 19:56:22.545295 6496 driver.c:196] driver service terminated successfully
nvidia-container-cli: initialization error: driver error: failed to process request

 - [ ] Kernel version from `uname -a
Linux nano 4.9.201-tegra NVIDIA/nvidia-docker#1 SMP PREEMPT Fri Feb 19 08:40:32 PST 2021 aarch64 aarch64 aarch64 GNU/Linux

 - [ ] 
 - [ ] Any relevant kernel output lines from `dmesg`
 - [ ] Driver information from `nvidia-smi -a`
./deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

Detected 1 CUDA Capable device(s)

Device 0: "NVIDIA Tegra X1"
  CUDA Driver Version / Runtime Version          10.2 / 10.2
  CUDA Capability Major/Minor version number:    5.3
  Total amount of global memory:                 3964 MBytes (4156694528 bytes)
  ( 1) Multiprocessors, (128) CUDA Cores/MP:     128 CUDA Cores
  GPU Max Clock rate:                            922 MHz (0.92 GHz)
  Memory Clock rate:                             13 Mhz
  Memory Bus Width:                              64-bit
  L2 Cache Size:                                 262144 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(65536), 2D=(65536, 65536), 3D=(4096, 4096, 4096)
  Maximum Layered 1D Texture Size, (num) layers  1D=(16384), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(16384, 16384), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 32768
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  2048
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 1 copy engine(s)
  Run time limit on kernels:                     Yes
  Integrated GPU sharing Host Memory:            Yes
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  Device supports Unified Addressing (UVA):      Yes
  Device supports Compute Preemption:            No
  Supports Cooperative Kernel Launch:            No
  Supports MultiDevice Co-op Kernel Launch:      No
  Device PCI Domain ID / Bus ID / location ID:   0 / 0 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >

deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 10.2, CUDA Runtime Version = 10.2, NumDevs = 1
Result = PASS

 - [ ] Docker version from `docker version`
 Docker version 19.03.15, build 99e3ed8

 - [ ] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
 ||/ Name                         Version             Architecture        Description
+++-============================-===================-===================-==============================================================
un  libgldispatch0-nvidia        <none>              <none>              (no description available)
ii  libnvidia-container-tools    1.3.3-1             arm64               NVIDIA container runtime library (command-line tools)
ii  libnvidia-container0:arm64   0.9.0~beta.1        arm64               NVIDIA container runtime library
ii  libnvidia-container1:arm64   1.3.3-1             arm64               NVIDIA container runtime library
un  nvidia-304                   <none>              <none>              (no description available)
un  nvidia-340                   <none>              <none>              (no description available)
un  nvidia-384                   <none>              <none>              (no description available)
un  nvidia-common                <none>              <none>              (no description available)
ii  nvidia-container-csv-cuda    10.2.89-1           arm64               Jetpack CUDA CSV file
ii  nvidia-container-csv-cudnn   8.0.0.180-1+cuda10. arm64               Jetpack CUDNN CSV file
ii  nvidia-container-csv-tensorr 7.1.3.0-1+cuda10.2  arm64               Jetpack TensorRT CSV file
ii  nvidia-container-csv-visionw 1.6.0.501           arm64               Jetpack VisionWorks CSV file
ii  nvidia-container-runtime     3.4.2-1             arm64               NVIDIA container runtime
un  nvidia-container-runtime-hoo <none>              <none>              (no description available)
ii  nvidia-container-toolkit     1.4.2-1             arm64               NVIDIA container runtime hook
un  nvidia-cuda-dev              <none>              <none>              (no description available)
ii  nvidia-l4t-3d-core           32.5.1-202102190845 arm64               NVIDIA GL EGL Package
ii  nvidia-l4t-apt-source        32.5.1-202102190845 arm64               NVIDIA L4T apt source list debian package
ii  nvidia-l4t-bootloader        32.5.1-202102190845 arm64               NVIDIA Bootloader Package
ii  nvidia-l4t-camera            32.5.1-202102190845 arm64               NVIDIA Camera Package
un  nvidia-l4t-ccp-t210ref       <none>              <none>              (no description available)
ii  nvidia-l4t-configs           32.5.1-202102190845 arm64               NVIDIA configs debian package
ii  nvidia-l4t-core              32.5.1-202102190845 arm64               NVIDIA Core Package
ii  nvidia-l4t-cuda              32.5.1-202102190845 arm64               NVIDIA CUDA Package
ii  nvidia-l4t-firmware          32.5.1-202102190845 arm64               NVIDIA Firmware Package
ii  nvidia-l4t-graphics-demos    32.5.1-202102190845 arm64               NVIDIA graphics demo applications
ii  nvidia-l4t-gstreamer         32.5.1-202102190845 arm64               NVIDIA GST Application files
ii  nvidia-l4t-init              32.5.1-202102190845 arm64               NVIDIA Init debian package
ii  nvidia-l4t-initrd            32.5.1-202102190845 arm64               NVIDIA initrd debian package
ii  nvidia-l4t-jetson-io         32.5.1-202102190845 arm64               NVIDIA Jetson.IO debian package
ii  nvidia-l4t-jetson-multimedia 32.5.1-202102190845 arm64               NVIDIA Jetson Multimedia API is a collection of lower-level AP
ii  nvidia-l4t-kernel            4.9.201-tegra-32.5. arm64               NVIDIA Kernel Package
ii  nvidia-l4t-kernel-dtbs       4.9.201-tegra-32.5. arm64               NVIDIA Kernel DTB Package
ii  nvidia-l4t-kernel-headers    4.9.201-tegra-32.5. arm64               NVIDIA Linux Tegra Kernel Headers Package
ii  nvidia-l4t-multimedia        32.5.1-202102190845 arm64               NVIDIA Multimedia Package
ii  nvidia-l4t-multimedia-utils  32.5.1-202102190845 arm64               NVIDIA Multimedia Package
ii  nvidia-l4t-oem-config        32.5.1-202102190845 arm64               NVIDIA OEM-Config Package
ii  nvidia-l4t-tools             32.5.1-202102190845 arm64               NVIDIA Public Test Tools Package
ii  nvidia-l4t-wayland           32.5.1-202102190845 arm64               NVIDIA Wayland Package
ii  nvidia-l4t-weston            32.5.1-202102190845 arm64               NVIDIA Weston Package
ii  nvidia-l4t-x11               32.5.1-202102190845 arm64               NVIDIA X11 Package
ii  nvidia-l4t-xusb-firmware     32.5.1-202102190845 arm64               NVIDIA USB Firmware Package
un  nvidia-libopencl1-dev        <none>              <none>              (no description available)
un  nvidia-prime                 <none>              <none>              (no description available)

 - [ ] NVIDIA container library version from `nvidia-container-cli -V`
 version: 1.3.3
build date: 2021-02-05T13:33+00:00
build revision: bd9fc3f2b642345301cb2e23de07ec5386232317
build compiler: aarch64-linux-gnu-gcc-7 7.5.0
build platform: aarch64
build flags: -D_GNU_SOURCE -D_FORTIFY_SOURCE=2 -DNDEBUG -std=gnu11 -O2 -g -fdata-sections -ffunction-sections -fstack-protector -fno-strict-aliasing -fvisibility=hidden -Wall -Wextra -Wcast-align -Wpointer-arith -Wmissing-prototypes -Wnonnull -Wwrite-strings -Wlogical-op -Wformat=2 -Wmissing-format-attribute -Winit-self -Wshadow -Wstrict-prototypes -Wunreachable-code -Wconversion -Wsign-conversion -Wno-unknown-warning-option -Wno-format-extra-args -Wno-gnu-alignof-expression -Wl,-zrelro -Wl,-znow -Wl,-zdefs -Wl,--gc-sections

 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))
 - [ ] Docker command, image and tag used

Description:
I started to remove Iptables (sudo apt remove iptables) and the package manager removed Docker and Nvidia-Docker in the process. All of the nvidia packages (sudo dpkg-query -l | grep nvidia) seem to be intact, however.

Other than reflashing the Jetson Nano with the SD Card image for Jetpack 4.5.1, is there a way to simply reinstall the correct version of Docker and Nvidia-Docker2 that was used in the original Jetpack image (https://developer.nvidia.com/jetson-nano-sd-card-image.zip)?

Also, can Docker be reinstalled with sudo or does Docker have to be installed as root (sudo su)?

I tried to reinstall Docker by following the instructions at the following links:

    [Installation Guide — NVIDIA Cloud Native Technologies documentation](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#docker)
    [Install Docker Engine on Ubuntu | Docker Documentation](https://docs.docker.com/engine/install/ubuntu/) 

Docker version 19.03 is working on the Nano. Verified by running " sudo docker run hello-world"
Nvidia-Docker (NVIDIA Container Toolkit) was also installed successfully.

However, when I verified the install using the following command, I ran into a run-time error: (Driver issue?)

Command: (Cuda 10)
docker run --gpus all -it --rm --network host --volume ~/nvdli-data:/nvdli-nano/data --device /dev/video0 nvcr.io/nvidia/dli/dli-nano-ai:v2.0.1-r32.5.0

Error:
docker: Error response from daemon: OCI runtime create failed: container_linux.g o:367: starting container process caused: process_linux.go:495: container init c aused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: nv idia-container-cli: initialization error: driver error: failed to process reques t: unknown.
----------------------------------
Nvidia's Response:
"The nvidia-docker2_2.2.0-1_all.deb is included in the JetPack.
Please use SDKmanager to download it (click reflash just for downloading the package)."
-----------------------------------

Can the debian package be downloaded/installed directly from the Nano using Apt package manager?

user@nano:~$ cat /etc/apt/sources.list.d/nvidia-container-runtime.list*

deb https://nvidia.github.io/libnvidia-container/stable/ubuntu18.04/$(ARCH) /

#deb https://nvidia.github.io/libnvidia-container/experimental/ubuntu18.04/$(ARCH) /

deb https://nvidia.github.io/nvidia-container-runtime/stable/ubuntu18.04/$(ARCH) /

#deb https://nvidia.github.io/nvidia-container-runtime/experimental/ubuntu18.04/$(ARCH) /

user@nano:~$ cat /etc/apt/sources.list.d/nvidia-docker.list

deb https://nvidia.github.io/libnvidia-container/stable/ubuntu18.04/$(ARCH) /

#deb https://nvidia.github.io/libnvidia-container/experimental/ubuntu18.04/$(ARCH) /

deb https://nvidia.github.io/nvidia-container-runtime/stable/ubuntu18.04/$(ARCH) /

#deb https://nvidia.github.io/nvidia-container-runtime/experimental/ubuntu18.04/$(ARCH) /

deb https://nvidia.github.io/nvidia-docker/ubuntu18.04/$(ARCH) /

**Comment by elezar** [comment]
I am closing this as it seems to have been caused by an incorrectly configured Docker daemon. If there are still problems, please reopen this or create a new issue.
