### ISSUE TITLE
exec format error？

### ISSUE THREAD

**Issue by Sjey-Lyn** [NVIDIA/nvidia-container-toolkit#303]
![image](https://github.com/NVIDIA/nvidia-container-toolkit/assets/74102271/63e67db3-e719-4b15-9128-2f85024478ca)
Can anybody tell me the solution？

**Comment by elezar** [comment]
@Sjey-Lyn could it be that the `ubuntu` image that you have locally is an `linux/arm64` image?

What is the output of:
```
docker inspect ubuntu | grep -i Architecture
```

**Comment by Sjey-Lyn** [comment]
I reinstall my nvidia driver and solve it

**Comment by elezar** [comment]
Thanks for confirming. Can we close this issue then?
