### ISSUE TITLE
Request for release `1.15-rc.2`

### ISSUE THREAD

**Issue by aaronmondal** [NVIDIA/nvidia-container-toolkit#304]
We're trying to bump the ctk in nixpkgs: https://github.com/NixOS/nixpkgs/pull/278969
Related https://github.com/NixOS/nixpkgs/pull/278607

The nixpkgs variant runs into segfaults caused by https://github.com/NVIDIA/go-nvml/issues/36 which have been fixed in `1.15.0-rc.1` but AFAICS the changes didn't make it into `1.14.4`.

Would it be possible to release `1.15.0-rc.2`? That would give us access to:
- Some `go.sum` update which bumped go-nvml
- The ldconfig-path patch in https://github.com/NVIDIA/nvidia-container-toolkit/commit/b3519fadc469229e920766c4be7fad0fb955fd35
- The docker CDI support from https://github.com/NVIDIA/nvidia-container-toolkit/commit/738ebd83d3269731fd7d39678294abad298c1193 (Related https://github.com/NixOS/nixpkgs/pull/278607)

**Comment by elezar** [comment]
@aaronmondal I have released https://github.com/NVIDIA/nvidia-container-toolkit/releases/tag/v1.15.0-rc.2

Please let me know if there are any problems on your end.

**Comment by elezar** [comment]
@aaronmondal just a note. We have just discovered a bug in the `v1.15.0-rc.2` release.

I have created #313 to address this and will publish a new release once that is in.

**Comment by aaronmondal** [comment]
@elezar Thanks for the heads up! I actually think I ran into this haha.

**Comment by elezar** [comment]
Hi @aaronmondal. We have since released `v1.15.0-rc.3` which includes a fix for the issue. Please let us know if there are any other problems.

**Comment by elezar** [comment]
Closing this issue as the releases are out.
