### ISSUE TITLE
debian bullseye cant update to 1.11.0~rc.3_1

### ISSUE THREAD

**Issue by euri10** [NVIDIA/nvidia-container-toolkit#31]
it seems it newly depends to nvidia-container-toolkit-base but the latter is not available

**Comment by elezar** [comment]
@euri10 thanks for bringing this to our attention. I will check why this package was included in the ubuntu repository but not debian.

**Comment by elezar** [comment]
There was an issue with our build infrastructure that meant that the `-base` package was not generated for the debian repositories. We are preparing to roll out a release of 1.11.0 in the next day or two and the package will be available then.

For the `nvidia-container-toolkit-base` package it should also be possible to install the [Ubuntu package](https://github.com/NVIDIA/libnvidia-container/blob/gh-pages/experimental/ubuntu18.04/amd64/nvidia-container-toolkit-base_1.11.0~rc.3-1_amd64.deb?raw=true) on recent debian sytems.

**Comment by euri10** [comment]
much appreciated @elezar ! I'll wait on having the real debian to avoid a [FrankenDebian](https://wiki.debian.org/DontBreakDebian#Don.27t_make_a_FrankenDebian) even if I'm sure this would be ok !
