### ISSUE TITLE
error processing package  nvidia-container-toolkit-base (--configure):

### ISSUE THREAD

**Issue by paulemurray** [NVIDIA/nvidia-container-toolkit#316]
Trying to install on OpenMediaVault Debian 12 with apt. Trying the command 
> sudo apt-get install -y nvidia-container-toolkit

Gives me this output

> The following additional packages will be installed:
  libnvidia-container-tools libnvidia-container1
The following NEW packages will be installed:
  libnvidia-container-tools libnvidia-container1 nvidia-container-toolkit
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
Need to get 0 B/1,865 kB of archives.
After this operation, 5,974 kB of additional disk space will be used.
Selecting previously unselected package libnvidia-container1:amd64.
(Reading database ... 63924 files and directories currently installed.)
Preparing to unpack .../libnvidia-container1_1.14.4-1_amd64.deb ...
Unpacking libnvidia-container1:amd64 (1.14.4-1) ...
Selecting previously unselected package libnvidia-container-tools.
Preparing to unpack .../libnvidia-container-tools_1.14.4-1_amd64.deb ...
Unpacking libnvidia-container-tools (1.14.4-1) ...
Selecting previously unselected package nvidia-container-toolkit.
Preparing to unpack .../nvidia-container-toolkit_1.14.4-1_amd64.deb ...
Unpacking nvidia-container-toolkit (1.14.4-1) ...
Setting up nvidia-container-toolkit-base (1.14.4-1) ...
ERRO[0000] unable to create config: (13, 35): unexpected token no value can start with n, was expecting a table key
dpkg: error processing package nvidia-container-toolkit-base (--configure):
 installed nvidia-container-toolkit-base package post-installation script subprocess returned error exit status 1
Setting up libnvidia-container1:amd64 (1.14.4-1) ...
Setting up libnvidia-container-tools (1.14.4-1) ...
dpkg: dependency problems prevent configuration of nvidia-container-toolkit:
 nvidia-container-toolkit depends on nvidia-container-toolkit-base (= 1.14.4-1); however:
  Package nvidia-container-toolkit-base is not configured yet.
dpkg: error processing package nvidia-container-toolkit (--configure):
 dependency problems - leaving unconfigured
Processing triggers for libc-bin (2.36-9+deb12u3) ...
Errors were encountered while processing:
 nvidia-container-toolkit-base
 nvidia-container-toolkit
E: Sub-process /usr/bin/dpkg returned an error code (1)

I've been unsuccessful in finding any help on Google for this issue. Following [this tutorial](https://tizutech.com/plex-transcoding-with-docker-nvidia-gpu/) and everything has been fine until this step. Nvidia-smi works fine so the GPU is being detected and usable. No clue what the issue could be

**Comment by elezar** [comment]
The `configure` command is trying to run the command here: https://github.com/NVIDIA/nvidia-container-toolkit/blob/d167812ce3a55ec04ae2582eff1654ec812f42e1/packaging/debian/nvidia-container-toolkit-base.postinst#L7

What does running:
```
nvidia-ctk config --config-file=/etc/nvidia-container-runtime/config.toml 
```
show on your sytem.

This should update `/etc/nvidia-container-runtime/config.toml` if required. Does that file exist on your system, and what are its contents?

**Comment by elezar** [comment]
As a santiy check, I have run the installation in a `debian:12` container and did not encounter the error you mentioned. This may be due to a config different though.

**Comment by paulemurray** [comment]
> The `configure` command is trying to run the command here:
> 
> https://github.com/NVIDIA/nvidia-container-toolkit/blob/d167812ce3a55ec04ae2582eff1654ec812f42e1/packaging/debian/nvidia-container-toolkit-base.postinst#L7
> 
> What does running:
> 
> ```
> nvidia-ctk config --config-file=/etc/nvidia-container-runtime/config.toml 
> ```
> 
> show on your sytem.
> 
> This should update `/etc/nvidia-container-runtime/config.toml` if required. Does that file exist on your system, and what are its contents?

Running nvidia-ctk outputs
>ERRO[0000] unable to create config: (13, 35): unexpected token no value can start with n, was expecting a table key

Contents of condig.toml
>disable-require = false
#swarm-resource = "DOCKER_RESOURCE_GPU"
accept-nvidia-visible-devices-envvar-when-unprivileged = true
#accept-nvidia-visible-devices-as-volume-mounts = false
[nvidia-container-cli]
#root = "/run/nvidia/driver" path = "/usr/bin/nvidia-container-cli"
environment = []
#debug = "/var/log/nvidia-container-toolkit.log" ldcache =
#"/etc/ld.so.cache"
load-kmods = true
#no-cgroups = false user = "root:video" ldconfig = "@/sbin/ldconfig"
#ldconfig = "/sbin/ldconfig"
ldconfig = "/sbin/ldconfig.real" [nvidia-container-runtime]
#debug = "/var/log/nvidia-container-runtime.log"

**Comment by paulemurray** [comment]
Didn't mean to close/reopen

**Comment by paulemurray** [comment]
Deleted the config.toml and everything works now. Thanks

**Comment by elezar** [comment]
@paulemurray just to clarify: Are those config file contents formatted as they exist on the system, meaning that we have the following lines:
```
#ldconfig = "/sbin/ldconfig"
ldconfig = "/sbin/ldconfig.real" [nvidia-container-runtime]
#debug = "/var/log/nvidia-container-runtime.log"
```
As a matter of interest, which version of the container toolkit was installed before you installed `1.14.4` and did you run any scripts to update the `config.toml` file?
