### ISSUE TITLE
Publish SLES 15 SP3 container-toolkit-image on ngc

### ISSUE THREAD

**Issue by faiq** [NVIDIA/nvidia-container-toolkit#37]
As a user of the gpu operator, I should be able to use the pods it deploys (container-toolkit) to configure my node with the necessary software to run GPU workloads on SLES-15 SP3.

Currently there is no image published in the [NGC catalog](https://catalog.ngc.nvidia.com/orgs/nvidia/teams/k8s/containers/container-toolkit/tags). This means I have to configure the node myself or maintain my own build of a container.

There is currently this [dockerfile](https://gitlab.com/nvidia/container-toolkit/container-toolkit/-/blob/main/docker/Dockerfile.opensuse-leap) in the repository. Is there any reason that it is not published?

Cross posted from https://gitlab.com/nvidia/container-toolkit/container-toolkit/-/issues/7

**Comment by elezar** [comment]
The primary limiting factor for deploying the NVIDIA Container Toolkit using the Toolkit Container is that the GLIBC version on the host is too old for the components being copied to the mounted filesystem. The only distribution where we have experienced this to be an issue is on Centos7 systems and as such these are the only ones where a different image needs to be used in the context of the GPU Operator. On all other sytems we use the Ubuntu or ubi8 images.

Do these images not work in your case?

The dockerfile you linked is used to build the opensuse packages and is not used for building the container image deployed as an GPUn Operator operand.

**Comment by faiq** [comment]
the following values makes it work 

```
toolkit:
  version: v1.10.0-ubi8
``` 

can this be added to documentation somewhere so folks don't need to experiment for themselves?

**Comment by elezar** [comment]
@shivamerla do you have a link to the documentation (if any) for this use case?

**Comment by shivamerla** [comment]
@elezar We have not covered this so far as SLES was not officially supported with operator. We will do that with upcoming release where we are planning to cover this distro.

**Comment by faiq** [comment]
@elezar @shivamerla you can go ahead and close this issue or maybe make a new one for your public tracker

**Comment by ATP-55** [comment]
@faiq I am trying to deploy gpu-operator on SLES 15 SP4, But I am not able to. Getting https://github.com/NVIDIA/gpu-operator/issues/443

I have tried to use the images you have suggested above but still no luck. Just checking if you also too facing the same issue or any suggestion please?

**Comment by faiq** [comment]
Unfortunately, we have never attempted with SP4.
