### ISSUE TITLE
GPU not running for Rviz and Gazebo simulation on docker container with Ros melodic base image 

### ISSUE THREAD

**Issue by ak78699** [NVIDIA/nvidia-container-toolkit#393]
I pulled the ROS Melodic base image and set up a Gazebo/RVIZ simulation package. However, the simulation continues to run on the CPU instead of the GPU. I set up the NVIDIA Container Toolkit and attempted to download NVIDIA Docker 2, which seems to have downloaded successfully. However, when I run nvidia-docker version, it shows @version@ instead of the actual version. I also have CUDA enabled on the host machine. When I run nvidia-smi within the container, it detects my GPU and CUDA version, but the simulation still doesn't use the GPU.

I'm trying to configure the containers within the ROS image to make it easier to set up simulations for my team. I'm assuming that if I pull an NVIDIA base image, I'd need to match the drivers with my entire team, as all of us have different computers. I'm not sure how to ensure that the simulation runs on Docker. I ran nvtop to check if the GPU was configured, but it wasn't.

Please let me know what I can do. I've read up on it quite a bit but still cannot make it work.

Here is my Dockerfile:

# Use ROS melodic as base image
FROM ros:melodic-ros-core-bionic

# To avoid prompts in setup
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install --no-install-recommends -y \
    lsb-release \
    curl \
    gnupg2 \
    sudo \
    software-properties-common

# Add a non-root user for pip & ardusub
ENV USER=sonar_test
RUN useradd -U -m $USER && \
    usermod -G users $USER

ENV HOME=/home/sonar_test
RUN echo "sonar_test ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/$USER
RUN echo 'Defaults env_keep += "DEBIAN_FRONTEND USER"' | EDITOR='tee -a' visudo
RUN chmod 0440 /etc/sudoers.d/$USER
USER $USER

# Install ROS Melodic
RUN sudo apt-get update && sudo apt-get install -y ros-melodic-desktop-full

# Install Git
RUN sudo apt-get install -y git; git config --global url."https://github.com/".insteadOf git://github.com/

# # Install Python 2.7 and Python 3
RUN sudo apt-get install -y python2.7 python3 python-pip python3-pip

# Install rosdep
RUN sudo apt-get install -y python-rosdep

# Initialize rosdep
RUN sudo rosdep init && \
    rosdep update && \
    sudo rosdep fix-permissions

RUN sudo apt-get install python-catkin-tools -y

RUN sudo apt-get install -y \
    ros-melodic-std-msgs \
    ros-melodic-geometry-msgs \
    ros-melodic-sensor-msgs \
    ros-melodic-message-to-tf \
    ros-melodic-robot-state-publisher \
    ros-melodic-image-transport \
    ros-melodic-cv-bridge 

# Install additional ROS packages
RUN sudo apt-get install --no-install-recommends -y \
    ros-melodic-uuv-simulator \
    ros-melodic-geodesy \
    ros-melodic-robot-localization

    # Install additional packages for GUI x 11 forwarding
RUN sudo apt-get update && sudo apt-get install -y \
    x11-apps \
    x11-xserver-utils \
    libgl1-mesa-glx \
    mesa-utils

# Set the working directory to the copied volume
COPY --chown=1000:1000 src $HOME/test_simulation/src
WORKDIR $HOME/test_simulation/src

# install version control in workspace  
RUN sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
RUN curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
RUN sudo apt-get update
RUN sudo apt-get install python-vcstool

# clone repository within the workspace;  
RUN git clone https://github.com/CapstoneROV/sonar_testing.git
RUN vcs import < ./sonar_testing/dependencies.repos

WORKDIR $HOME/test_simulation
# Make workspace
RUN /bin/bash -c "source /opt/ros/melodic/setup.bash && catkin build"  
RUN echo "source $HOME/test_simulation/devel/setup.bash" >> ~/.bashrc

# # Set the default command to bash
CMD exec bash

Here is my makefile: 
IMAGE_NAME= sonar-testing
CONTAINER_NAME = test_simulation
USER = sonar_test

.PHONY: build
build:
	docker build -t $(IMAGE_NAME) .

# build interactive ros image using GPUs; 
run:
	docker run -it	 \
	--privileged \
	--env="DISPLAY" --env="QT_X11_NO_MITSHM=1" \
	--volume="/tmp/.X11-unix:/tmp/.X11-unix:rw" \
	--runtime=nvidia --gpus all $(IMAGE_NAME) 

# Run docker container with user ardupilot
run_container:
	sudo docker run --rm -it --user $(USER) --privileged --cap-add SYS_ADMIN --device /dev/fuse \
	--env="DISPLAY" --env="QT_X11_NO_MITSHM=1" \
	--volume="/tmp/.X11-unix:/tmp/.X11-unix:rw" --name $(CONTAINER_NAME) \
        --runtime=nvidia --gpus all \
	-w /home/$(USER)/$(CONTAINER_NAME) $(IMAGE_NAME)

# Make catkin workspace add source devel/setup.bash to bashrc
catkin_make:
	sudo docker exec -it $(CONTAINER_NAME) /bin/bash -c "source /opt/ros/melodic/setup.bash && \
	cd /$(CONTAINER_NAME) && \
	catkin_make" && \
	echo "source /$(CONTAINER_NAME)/devel/setup.bash" >> ~/.bashrc

# Launch sim.launch
launch_sim:
	sudo docker exec -it $(CONTAINER_NAME) /bin/bash -c "source /opt/ros/melodic/setup.bash && \
	cd /$(CONTAINER_NAME) && \
	roslaunch capstone sim.launch"

# Docker json file: 
{
 "default-runtime": "nvidia",
  "runtimes": {
     "nvidia": {
         "path": "/usr/bin/nvidia-container-runtime",
         "runtimeArgs": []
     }
 }
}

#LibGL error: additionally i continue to have libGL errors

**Comment by elezar** [comment]
@ak78699 `nvidia-docker` is deprecated. Please check the installation instructions for setting up the NVIDIA Container Toolkit: https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html 

Also confirm that you're running a recent version of the toolkit.

Since you mention `libGL`, it may be that you do not have the right driver capabilities set when running your container. This can be changed by adding the `-e NVIDIA_DRIVER_CAPABILITIES=all` to your `docker run` command line. For example:
```
docker run -it
--privileged
--env="DISPLAY" --env="QT_X11_NO_MITSHM=1"
--volume="/tmp/.X11-unix:/tmp/.X11-unix:rw"
--runtime=nvidia --gpus all -e NVIDIA_DRIVER_CAPABILITIES=all $(IMAGE_NAME)
```

**Comment by ak78699** [comment]
Thank you for your response! It turned out that I had  integrated graphics within my CPU. This was confusing the container and they couldn't run on the NVIDIA drivers. Disabling the integrated graphics in the BIOS seemed to fix the problem, and now RVIZ and Gazebo are running on GPU.
