### ISSUE TITLE
sample CUDA container does not work on my ubuntu 22 PC

### ISSUE THREAD

**Issue by achataigner** [NVIDIA/nvidia-container-toolkit#396]
Hi,

The classic sample does not work on my ubuntu22 PC (it was working fine on ubuntu 20):
 `sudo docker run --rm --runtime=nvidia --gpus all ubuntu nvidia-smi`

docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: mount error: failed to add device rules: unable to generate new device filter program from existing programs: unable to create new device filters program: load program: invalid argument: last insn is not an exit or jmp
processed 0 insns (limit 1000000) max_states_per_insn 0 total_states 0 peak_states 0 mark_read 0: unknown.

[nvidia-container-runtime.log](https://github.com/NVIDIA/nvidia-container-toolkit/files/14526499/nvidia-container-runtime.log)
[nvidia-container-toolkit.log](https://github.com/NVIDIA/nvidia-container-toolkit/files/14526500/nvidia-container-toolkit.log)
[nvidia-smi.log](https://github.com/NVIDIA/nvidia-container-toolkit/files/14526501/nvidia-smi.log)

OS: Ubuntu 22.04

Kernel version: 5.15.0-97-generic #107-Ubuntu SMP Wed Feb 7 13:26:48 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

Docker version 25.0.4, build 1a576c5

**Comment by achataigner** [comment]
@elezar any idea ?

**Comment by elezar** [comment]
@achataigner could you confirm your NVIDIA Container Toolkit version?

The issue is occurring when we are trying to update the cgroupv2 eBPF program that controls device access to allow access to the NVIDIA devices that are being injected into the container.

Could you confirm that you are using either cgroup v1 or cgroup v2 and not a hybrid configuration?

**Comment by achataigner** [comment]
`nvidia-container-toolkit --version` result:

NVIDIA Container Runtime Hook version 1.14.6
commit: 5605d191332dcfeea802c4497360d60a65c7887e

`grep cgroup /proc/filesystems` result:

nodev	cgroup
nodev	cgroup2

Thanks a lot for your help

**Comment by achataigner** [comment]
I have another PC on which nvidia-container-toolkit works well.
Same nvidia-container-toolkit version, running also cgroup v2.

`sudo docker run --rm --runtime=nvidia --gpus all ubuntu nvidia-smi` result:
`Wed Mar 13 09:35:26 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.23.08              Driver Version: 545.23.08    CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 2060 ...    On  | 00000000:01:00.0 Off |                  N/A |
| 43%   30C    P8               4W / 175W |     54MiB /  8192MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
+---------------------------------------------------------------------------------------+
`

**Comment by achataigner** [comment]
@elezar do you have any suggestion ?

**Comment by elezar** [comment]
@achataigner your comment from https://github.com/NVIDIA/nvidia-container-toolkit/issues/396#issuecomment-1993839095 doesn't confirm that you're running a hybrid cgroup configuration or not (although two cgroup filesystem entries indicate that this may be the case). Is this also the case on the system that works.

Could you run:
```
[ $(stat -fc %T /sys/fs/cgroup/) = "cgroup2fs" ] && echo "unified" || ( [ -e /sys/fs/cgroup/unified/ ] && echo "hybrid" || echo "legacy")
```
on each machine?

(This was taken from [here](https://unix.stackexchange.com/questions/480747/how-to-find-out-if-systemd-uses-legacy-hybrid-or-unified-mode-cgroupsv1-vs-cgr)).

**Comment by achataigner** [comment]
On my PC with the problem:
unified

On the PC without any problem:
unified

**Comment by achataigner** [comment]
@elezar another idea ?

**Comment by achataigner** [comment]
Anything new ?

**Comment by achataigner** [comment]
@elezar What is the status of this issue ? Can I do anything to help you ? Any other place where I can report this issue to get a fix quicker ?
Regards

**Comment by elezar** [comment]
What are the differences between the two systems? Is docker installed differently on one of them? Are they using different driver versions? Are the runc versions the same?

One option would be to upgrade to the v1.15.0-rc.4 version of the NVIDIA Container Toolkit and use the experimental automatic CDI runtime mode. Run the following:

```
docker run --runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=runtime.nvidia.com/gpu=all ubuntu nvidia-smi
```

Alternatively, since you are using docker 25 you could use the native opt-in CDI support.

To enable this in docker run:
```
sudo nvidia-ctk runtime configure --runtime docker --cdi-enabled
sudo systemctl restart docker
```
Now, it is still required to generate CDI specifications for installed devices.
```
sudo nvidia-ctk cdi generate --output /var/run/cdi/nvidia.yaml
```
Note that this needs to be re-run at boot or when the driver configuration changes.

**Comment by achataigner** [comment]
"What are the differences between the two systems?"
I don't see one except for the graphics card
Same OS
Same Kernel version
Same Docker version
Same nvidia-container-toolkit version
Same cgroup version

"Is docker installed differently on one of them? "
No

Driver versions:
nvidia-smi.log already provided for both machines in previous posts:
Machine OK: 545.23.08
Machine KO: 545.29.06
Is it possible to use exactly the same versions ? I only used the "additional drivers" tool of ubuntu.

Are the runc versions the same?
runc --version prints:

Machine OK: 
runc version 1.1.12
commit: v1.1.12-0-g51d5e94
spec: 1.0.2-dev
go: go1.21.8
libseccomp: 2.5.3


Machine KO: 
runc version 1.1.12
commit: v1.1.12-0-g51d5e94
spec: 1.0.2-dev
go: go1.20.13
libseccomp: 2.5.3

I used dist-upgrade to upgrade ubuntu 20 to ubuntu 22 on both machines.
Do you think I could get different result if I reinstall ubuntu22 on the KO machine ?

**Comment by achataigner** [comment]
**Test 1** upgrade to the v1.15.0-rc.4 version: how can I install it ? Should I build it ?

**Test 2** :  use the native opt-in CDI support.
Still the same problem (some warnings appeared during nvidia-ctk cdi generate)

`
aymeric@aymeric-hp-zbook-15-g6-zbook-15-g6:/mnt/disk/dev/mytools$ sudo nvidia-ctk runtime configure --runtime docker --cdi.enabled
INFO[0000] Loading config from /etc/docker/daemon.json  
INFO[0000] Wrote updated config to /etc/docker/daemon.json 
INFO[0000] It is recommended that docker daemon be restarted. 
aymeric@aymeric-hp-zbook-15-g6-zbook-15-g6:/mnt/disk/dev/mytools$ sudo systemctl restart docker
aymeric@aymeric-hp-zbook-15-g6-zbook-15-g6:/mnt/disk/dev/mytools$ sudo nvidia-ctk cdi generate --output /var/run/cdi/nvidia.yaml
INFO[0000] Auto-detected mode as "nvml"                 
INFO[0000] Selecting /dev/nvidia0 as /dev/nvidia0       
INFO[0000] Selecting /dev/dri/card0 as /dev/dri/card0   
WARN[0000] Could not locate /dev/dri/controlD64: pattern /dev/dri/controlD64 not found 
INFO[0000] Selecting /dev/dri/renderD128 as /dev/dri/renderD128 
WARN[0000] Ignoring 32-bit libraries for libcuda.so: [/lib/i386-linux-gnu/libcuda.so.545.29.06] 
INFO[0000] Using driver version 545.29.06               
WARN[0000] Ignoring 32-bit libraries for libcuda.so: [/lib/i386-linux-gnu/libcuda.so.545.29.06] 
INFO[0000] Selecting /dev/nvidia-modeset as /dev/nvidia-modeset 
INFO[0000] Selecting /dev/nvidia-uvm-tools as /dev/nvidia-uvm-tools 
INFO[0000] Selecting /dev/nvidia-uvm as /dev/nvidia-uvm 
INFO[0000] Selecting /dev/nvidiactl as /dev/nvidiactl   
INFO[0000] Selecting /lib/x86_64-linux-gnu/libnvidia-egl-gbm.so.1.1.0 as /lib/x86_64-linux-gnu/libnvidia-egl-gbm.so.1.1.0 
INFO[0000] Selecting /usr/share/glvnd/egl_vendor.d/10_nvidia.json as /usr/share/glvnd/egl_vendor.d/10_nvidia.json 
INFO[0000] Selecting /usr/share/vulkan/icd.d/nvidia_icd.json as /usr/share/vulkan/icd.d/nvidia_icd.json 
WARN[0000] Could not locate vulkan/icd.d/nvidia_layers.json: pattern vulkan/icd.d/nvidia_layers.json not found 
INFO[0000] Selecting /usr/share/vulkan/implicit_layer.d/nvidia_layers.json as /usr/share/vulkan/implicit_layer.d/nvidia_layers.json 
INFO[0000] Selecting /usr/share/egl/egl_external_platform.d/15_nvidia_gbm.json as /usr/share/egl/egl_external_platform.d/15_nvidia_gbm.json 
WARN[0000] Could not locate egl/egl_external_platform.d/10_nvidia_wayland.json: pattern egl/egl_external_platform.d/10_nvidia_wayland.json not found 
INFO[0000] Selecting /usr/share/nvidia/nvoptix.bin as /usr/share/nvidia/nvoptix.bin 
INFO[0000] Selecting /lib/x86_64-linux-gnu/nvidia/xorg/nvidia_drv.so as /lib/x86_64-linux-gnu/nvidia/xorg/nvidia_drv.so 
INFO[0000] Selecting /lib/x86_64-linux-gnu/nvidia/xorg/libglxserver_nvidia.so.545.29.06 as /lib/x86_64-linux-gnu/nvidia/xorg/libglxserver_nvidia.so.545.29.06 
INFO[0000] Selecting /usr/share/X11/xorg.conf.d/10-nvidia.conf as /usr/share/X11/xorg.conf.d/10-nvidia.conf 
INFO[0000] Selecting /lib/x86_64-linux-gnu/libEGL_nvidia.so.545.29.06 as /lib/x86_64-linux-gnu/libEGL_nvidia.so.545.29.06 
INFO[0000] Selecting /lib/x86_64-linux-gnu/libGLESv1_CM_nvidia.so.545.29.06 as /lib/x86_64-linux-gnu/libGLESv1_CM_nvidia.so.545.29.06 
INFO[0000] Selecting /lib/x86_64-linux-gnu/libGLESv2_nvidia.so.545.29.06 as /lib/x86_64-linux-gnu/libGLESv2_nvidia.so.545.29.06 
INFO[0000] Selecting /lib/x86_64-linux-gnu/libGLX_nvidia.so.545.29.06 as /lib/x86_64-linux-gnu/libGLX_nvidia.so.545.29.06 
INFO[0000] Selecting /lib/x86_64-linux-gnu/libcuda.so.545.29.06 as /lib/x86_64-linux-gnu/libcuda.so.545.29.06 
INFO[0000] Selecting /lib/x86_64-linux-gnu/libcudadebugger.so.545.29.06 as /lib/x86_64-linux-gnu/libcudadebugger.so.545.29.06 
INFO[0000] Selecting /lib/x86_64-linux-gnu/libnvcuvid.so.545.29.06 as /lib/x86_64-linux-gnu/libnvcuvid.so.545.29.06 
INFO[0000] Selecting /lib/x86_64-linux-gnu/libnvidia-allocator.so.545.29.06 as /lib/x86_64-linux-gnu/libnvidia-allocator.so.545.29.06 
INFO[0000] Selecting /lib/x86_64-linux-gnu/libnvidia-cfg.so.545.29.06 as /lib/x86_64-linux-gnu/libnvidia-cfg.so.545.29.06 
INFO[0000] Selecting /lib/x86_64-linux-gnu/libnvidia-eglcore.so.545.29.06 as /lib/x86_64-linux-gnu/libnvidia-eglcore.so.545.29.06 
INFO[0000] Selecting /lib/x86_64-linux-gnu/libnvidia-encode.so.545.29.06 as /lib/x86_64-linux-gnu/libnvidia-encode.so.545.29.06 
INFO[0000] Selecting /lib/x86_64-linux-gnu/libnvidia-fbc.so.545.29.06 as /lib/x86_64-linux-gnu/libnvidia-fbc.so.545.29.06 
INFO[0000] Selecting /lib/x86_64-linux-gnu/libnvidia-glcore.so.545.29.06 as /lib/x86_64-linux-gnu/libnvidia-glcore.so.545.29.06 
INFO[0000] Selecting /lib/x86_64-linux-gnu/libnvidia-glsi.so.545.29.06 as /lib/x86_64-linux-gnu/libnvidia-glsi.so.545.29.06 
INFO[0000] Selecting /lib/x86_64-linux-gnu/libnvidia-glvkspirv.so.545.29.06 as /lib/x86_64-linux-gnu/libnvidia-glvkspirv.so.545.29.06 
INFO[0000] Selecting /lib/x86_64-linux-gnu/libnvidia-gpucomp.so.545.29.06 as /lib/x86_64-linux-gnu/libnvidia-gpucomp.so.545.29.06 
INFO[0000] Selecting /lib/x86_64-linux-gnu/libnvidia-ml.so.545.29.06 as /lib/x86_64-linux-gnu/libnvidia-ml.so.545.29.06 
INFO[0000] Selecting /lib/x86_64-linux-gnu/libnvidia-ngx.so.545.29.06 as /lib/x86_64-linux-gnu/libnvidia-ngx.so.545.29.06 
INFO[0000] Selecting /lib/x86_64-linux-gnu/libnvidia-nvvm.so.545.29.06 as /lib/x86_64-linux-gnu/libnvidia-nvvm.so.545.29.06 
INFO[0000] Selecting /lib/x86_64-linux-gnu/libnvidia-opencl.so.545.29.06 as /lib/x86_64-linux-gnu/libnvidia-opencl.so.545.29.06 
INFO[0000] Selecting /lib/x86_64-linux-gnu/libnvidia-opticalflow.so.545.29.06 as /lib/x86_64-linux-gnu/libnvidia-opticalflow.so.545.29.06 
INFO[0000] Selecting /lib/x86_64-linux-gnu/libnvidia-pkcs11-openssl3.so.545.29.06 as /lib/x86_64-linux-gnu/libnvidia-pkcs11-openssl3.so.545.29.06 
INFO[0000] Selecting /lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.545.29.06 as /lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.545.29.06 
INFO[0000] Selecting /lib/x86_64-linux-gnu/libnvidia-rtcore.so.545.29.06 as /lib/x86_64-linux-gnu/libnvidia-rtcore.so.545.29.06 
INFO[0000] Selecting /lib/x86_64-linux-gnu/libnvidia-tls.so.545.29.06 as /lib/x86_64-linux-gnu/libnvidia-tls.so.545.29.06 
INFO[0000] Selecting /lib/x86_64-linux-gnu/libnvoptix.so.545.29.06 as /lib/x86_64-linux-gnu/libnvoptix.so.545.29.06 
INFO[0000] Selecting /run/nvidia-persistenced/socket as /run/nvidia-persistenced/socket 
WARN[0000] Could not locate /nvidia-fabricmanager/socket: pattern /nvidia-fabricmanager/socket not found 
WARN[0000] Could not locate /tmp/nvidia-mps: pattern /tmp/nvidia-mps not found 
INFO[0000] Selecting /lib/firmware/nvidia/545.29.06/gsp_ga10x.bin as /lib/firmware/nvidia/545.29.06/gsp_ga10x.bin 
INFO[0000] Selecting /lib/firmware/nvidia/545.29.06/gsp_tu10x.bin as /lib/firmware/nvidia/545.29.06/gsp_tu10x.bin 
INFO[0000] Selecting /usr/bin/nvidia-smi as /usr/bin/nvidia-smi 
INFO[0000] Selecting /usr/bin/nvidia-debugdump as /usr/bin/nvidia-debugdump 
INFO[0000] Selecting /usr/bin/nvidia-persistenced as /usr/bin/nvidia-persistenced 
INFO[0000] Selecting /usr/bin/nvidia-cuda-mps-control as /usr/bin/nvidia-cuda-mps-control 
INFO[0000] Selecting /usr/bin/nvidia-cuda-mps-server as /usr/bin/nvidia-cuda-mps-server 
INFO[0000] Generated CDI spec with version 0.5.0        
aymeric@aymeric-hp-zbook-15-g6-zbook-15-g6:/mnt/disk/dev/mytools$ sudo docker run --rm --runtime=nvidia --gpus all ubuntu nvidia-smi
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: mount error: failed to add device rules: unable to generate new device filter program from existing programs: unable to create new device filters program: load program: invalid argument: last insn is not an exit or jmp
processed 0 insns (limit 1000000) max_states_per_insn 0 total_states 0 peak_states 0 mark_read 0: unknown.
`

**Comment by achataigner** [comment]
**Test 3**
Use nvidia driver 545.23.08 on machine KO : still KO

**Comment by elezar** [comment]
Please note the difference in docker commands when running with CDI.

**Comment by achataigner** [comment]
Sorry for that, running with CDI works !
Thanks a lot
