### ISSUE TITLE
Support for Ubuntu 22.10

### ISSUE THREAD

**Issue by databoy2k** [NVIDIA/nvidia-container-toolkit#41]
Is there a workaround or side-install for the toolkit on Ubuntu 11.10? There are no matching apt sources for this distro.

Thanks.

--Edit-- Finally found the workaround. The current system works on 22.10; you just have to re-name the distribution in the links to "ubuntu22.04". The link that worked was:

`curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg       && curl -s -L https://nvidia.github.io/libnvidia-container/ubuntu22.04/libnvidia-container.list |             sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' |             sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list`

With that said, this issue could be resolved by opening a source for "ubuntu22.10". 

Thanks.

**Comment by elezar** [comment]
Using the `ubuntu18.04` packages should work on all later ubuntu distributions.

Closing this issue. Please reopen if required.
