### ISSUE TITLE
nvml not recognizing my gpu

### ISSUE THREAD

**Issue by dess890** [NVIDIA/nvidia-container-toolkit#42]
Trying to run a visual locally which uses various docker containers and cuda to process everything. One of my containers is unhealthy because nvml isnt recognizing my gpu, causing the visualization to fail. I have a 3090 and im running on ubuntu
![Screenshot from 2022-12-28 09-26-42](https://user-images.githubusercontent.com/87389186/209827904-e9e4f4f1-a92a-4346-ba17-5a9adcaffb1b.png)

**Comment by klueska** [comment]
I've transferred the issue to the `nvidia-container-toolkit` repository.

Can you confirm how you are running this container and what version of the nvidia-container-toolkit you have installed?

**Comment by klueska** [comment]
Closing due to lack of inactivity. Please reopen if you are still having this issue.
