### ISSUE TITLE
apt mirror does not follow standard layout

### ISSUE THREAD

**Issue by humanoid2050** [NVIDIA/nvidia-container-toolkit#45]
The apt repository hosted at https://nvidia.github.io/libnvidia-container/stable/$distribution/$arch does not follow the standard apt repository layout. While apt does understand flat repositories, other tools which expect the standard layout of dists/$dist/$component fail when interacting with this unusual design. Please update to follow standard design patterns.

**Comment by elezar** [comment]
Thanks @humanoid2050. We are in the process of migrating our repositories off the github pages hosted version that we currently use and will ensure that this is addressed as part of that. It is unlikely that we will update the layout of this repository which will be maintained for backward-compatibility at that stage.
