### ISSUE TITLE
how to disable all gpu while default behavor

### ISSUE THREAD

**Issue by zhangguanzhang** [NVIDIA/nvidia-container-toolkit#451]
how to disable all gpu while default behavor
```
$ nvidia-container-toolkit --version
NVIDIA Container Runtime Hook version 1.13.5
commit: 6b8589dcb4dead72ab64f14a5912886e6165c079
$ nvidia-smi
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.113.01             Driver Version: 535.113.01   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
```
I found that I can see all gpu cards without any parameters
```
$ docker run --rm nvidia/cuda:12.4.0-base-ubuntu22.04 nvidia-smi -L
GPU 0: NVIDIA GeForce RTX 4090 (UUID: GPU-xxx-e0bf-xxx-60d4-xxxxxxx)
GPU 1: NVIDIA GeForce RTX 4090 (UUID: GPU-xxx-0a24-xxx-8faa-xxxxxxx)
GPU 2: NVIDIA GeForce RTX 4090 (UUID: GPU-xxx-5672-xxx-e60d-xxxxxxx)
GPU 3: NVIDIA GeForce RTX 4090 (UUID: GPU-xxx-b69f-xxx-f9c8-xxxxxxx)
GPU 4: NVIDIA GeForce RTX 4090 (UUID: GPU-xxx-6e8a-xxx-a75a-xxxxxxx)
GPU 5: NVIDIA GeForce RTX 4090 (UUID: GPU-xxx-357b-xxx-d26c-xxxxxxx)
GPU 6: NVIDIA GeForce RTX 4090 (UUID: GPU-xxx-e06c-xxx-d1dc-xxxxxxx)
GPU 7: NVIDIA GeForce RTX 4090 (UUID: GPU-xxx-4e2f-xxx-995f-xxxxxxx)
$ docker run --rm --gpus all nvidia/cuda:12.4.0-base-ubuntu22.04 nvidia-smi -L
GPU 0: NVIDIA GeForce RTX 4090 (UUID: GPU-xxx-e0bf-xxx-60d4-xxxxxxx)
GPU 1: NVIDIA GeForce RTX 4090 (UUID: GPU-xxx-0a24-xxx-8faa-xxxxxxx)
GPU 2: NVIDIA GeForce RTX 4090 (UUID: GPU-xxx-5672-xxx-e60d-xxxxxxx)
GPU 3: NVIDIA GeForce RTX 4090 (UUID: GPU-xxx-b69f-xxx-f9c8-xxxxxxx)
GPU 4: NVIDIA GeForce RTX 4090 (UUID: GPU-xxx-6e8a-xxx-a75a-xxxxxxx)
GPU 5: NVIDIA GeForce RTX 4090 (UUID: GPU-xxx-357b-xxx-d26c-xxxxxxx)
GPU 6: NVIDIA GeForce RTX 4090 (UUID: GPU-xxx-e06c-xxx-d1dc-xxxxxxx)
GPU 7: NVIDIA GeForce RTX 4090 (UUID: GPU-xxx-4e2f-xxx-995f-xxxxxxx)
```

🤔

**Comment by elezar** [comment]
Is nvidia set as your default runtime? Alternatively you can override the NVIDIA_VISIBLE_DEVICES envvar in the container to void.

**Comment by zhangguanzhang** [comment]
> Is nvidia set as your default runtime? Alternatively you can override the NVIDIA_VISIBLE_DEVICES envvar in the container to void.

It's  default runtime, but I think that without setting any variables, the gpu is not allocated

**Comment by elezar** [comment]
> but I think that without setting any variables, the gpu is not allocated

The issue is that the `nvidia/cuda:12.4.0-base-ubuntu22.04` has `NVIDIA_VISIBLE_DEVICES=all` set in the Docker image. This causes all devices to be injected when the `nvidia` runtime is used whether the user requested these or not.

**Comment by zhangguanzhang** [comment]
> > but I think that without setting any variables, the gpu is not allocated
> 
> The issue is that the `nvidia/cuda:12.4.0-base-ubuntu22.04` has `NVIDIA_VISIBLE_DEVICES=all` set in the Docker image. This causes all devices to be injected when the `nvidia` runtime is used whether the user requested these or not.

Thanks for pointing me in some directions, I'll take a look at this piece of information when I get to work tomorrow.
