### ISSUE TITLE
RTX 4070 not supported for docker

### ISSUE THREAD

**Issue by IshraqAtUCF** [NVIDIA/nvidia-container-toolkit#472]
I was trying to build one of NVIDIA's repo [AutoDMP ](https://github.com/NVlabs/AutoDMP?tab=readme-ov-file) successfully was able to build with the Dockerfile that was provided. However, I am unable to run the dockerfile with my GPU (RTX 4070) enabled. I followed the [Driver Installation](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html) guideline and ran the sample workload to verify my installation. 

But when I use docker to `docker run --gpus all -t autodmp` to run the docker image, it says

 _WARNING: Detected NVIDIA NVIDIA GeForce RTX 4070 GPU, which is not yet supported in this version of the container ERROR: No supported GPU(s) detected to run this container_

**Comment by IshraqAtUCF** [comment]
It does run the sample workload. Does that mean that it is an issue with AutoDMP?

**Comment by elezar** [comment]
@IshraqAtUCF yes. Please create an issue there. Feel free to repopen this if it is determined that there is a gap in the support of the NVIDIA Container Toolkit.

**Comment by Mactarvish** [comment]
Seems RTX 4060 LAPTOP is not supported too
