### ISSUE TITLE
Support for Ubuntu 24.04

### ISSUE THREAD

**Issue by awilhelm-projects** [NVIDIA/nvidia-container-toolkit#482]
Please add support for Ubuntu 24.04.

**Comment by sebastienmascha** [comment]
I was able to install and run the NVIDIA container with a Ubuntu 24.04 host using the `nvidia/cuda:11.7.1-cudnn8-devel-ubuntu22.04` container.

## Installation
Source: https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#linux-distributions
```bash
curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg \
  && curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | \
    sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
    sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
```
Update the packages list from the repository: `sudo apt-get update`
Install the NVIDIA Container Toolkit packages: `sudo apt-get install -y nvidia-container-toolkit`

# Usage
As before: docker run --runtime nvidia  -it nvidia/cuda:11.7.1-cudnn8-devel-ubuntu22.04 bash

**Comment by amirian** [comment]
> It will be great, if you can update the site : https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/supported-platforms.html and add Ubuntu 24.04.

This link also shows no support for v. 24.04: https://nvidia.github.io/libnvidia-container/ubuntu24.04/libnvidia-container.list

**Comment by amirian** [comment]
> Ubuntu 24.04 is supported.
> 
> The instructions at https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html should be compatible with Ubuntu 24.04.
> 
> If there are specific errors that are raised please open an issue accordingly.

but [this link](https://nvidia.github.io/libnvidia-container/ubuntu24.04/libnvidia-container.list) shows no support for 24.04 as for previous versions. It may be updated to match conventional installations if there is any official support.

**Comment by elezar** [comment]
@amirian the page you link to is a generic 404 page that doesn't explicitlt mention any ubuntu version.

Could you describe what kind of change you would like on the page to make it clear that it is possible to install the NVIDIA Container Toolkit packages on Ubuntu 24.04?

**Comment by amirian** [comment]
> @amirian the page you link to is a generic 404 page that doesn't explicitly mention any ubuntu version.
> 
> Could you describe what kind of change you would like on the page to make it clear that it is possible to install the NVIDIA Container Toolkit packages on Ubuntu 24.04?

The link is generated by an installation script which puts the Linux generation in the middle and gets repo. Simply change 24.04 to 22.04 in the link to see what you fetch.

**Comment by elezar** [comment]
As called out here https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#installing-with-apt the installation instructions are no longer distribution dependent (Basically `stable/deb` has replaced the previous `DISTRIBUTION` variable in the installation instructions).

Is this a script that you manage, or is it part of an opensource project where I can submit a patch?

**Comment by amirian** [comment]
> As called out here https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#installing-with-apt the installation instructions are no longer distribution dependent (Basically `stable/deb` has replaced the previous `DISTRIBUTION` variable in the installation instructions).
> 
> Is this a script that you manage, or is it part of an opensource project where I can submit a patch?

I cannot remember where I exactly got the script from, perhaps [this one](https://github.com/NVIDIA/nvidia-docker/issues/1731#issuecomment-1427484565). Good news of distribution independence, however, supporting non-updated old scripts would be helpful

**Comment by qdii** [comment]
@elezar The helm chart has no image for ubuntu24 https://catalog.ngc.nvidia.com/orgs/nvidia/containers/driver/tags

**Comment by florath** [comment]
I do not understand if this is now fixed or not.
Currently I get the same output as mabu-ibm: `Failed to pull image "nvcr.io/nvidia/driver:550.127.05-ubuntu24.04"` on a bre-metal installation (3 controller + 3 worker nodes)

Changing the image to `-ubuntu22.04` does not help as it runs into the following error:

```
-> done.
-> Kernel module compilation complete.
-> Unable to determine if Secure Boot is enabled: No such file or directory
ERROR: Unable to load the kernel module 'nvidia.ko'.  This happens most frequently when this kernel module was built against the wrong or improperly configured kernel sources, with a version of gcc that differs from the one used to build the target kernel, or if another driver, such as nouveau, is present and prevents the NVIDIA kernel module from obtaining ownership of the NVIDIA device(s), or no NVIDIA device installed in this system is supported by this NVIDIA Linux graphics driver release.
-> Kernel module load error: Invalid argument
-> Kernel messages:
[25536.796295] ecc: disagrees about version of symbol __fentry__
[25536.796299] ecc: Unknown symbol __fentry__ (err -22)
[25536.883206] nvidia: disagrees about version of symbol sme_me_mask
[25536.883214] nvidia: Unknown symbol sme_me_mask (err -22)
[25907.120025] iommufd: disagrees about version of symbol pin_user_pages_fast
[25907.120031] iommufd: Unknown symbol pin_user_pages_fast (err -22)
[25907.146347] mdev: disagrees about version of symbol __init_rwsem
[25907.146351] mdev: Unknown symbol __init_rwsem (err -22)
[25907.180800] iommufd: disagrees about version of symbol pin_user_pages_fast
[25907.180804] iommufd: Unknown symbol pin_user_pages_fast (err -22)
[25907.192932] ecc: disagrees about version of symbol __fentry__
[25907.192936] ecc: Unknown symbol __fentry__ (err -22)
[25907.275829] nvidia: disagrees about version of symbol sme_me_mask
[25907.275836] nvidia: Unknown symbol sme_me_mask (err -22)
[26272.992313] iommufd: disagrees about version of symbol pin_user_pages_fast
[26272.992319] iommufd: Unknown symbol pin_user_pages_fast (err -22)
[26273.014985] mdev: disagrees about version of symbol __init_rwsem
[26273.014989] mdev: Unknown symbol __init_rwsem (err -22)
[26273.050529] iommufd: disagrees about version of symbol pin_user_pages_fast
[26273.050533] iommufd: Unknown symbol pin_user_pages_fast (err -22)
[26273.074946] ecc: disagrees about version of symbol __fentry__
[26273.074950] ecc: Unknown symbol __fentry__ (err -22)
[26273.128888] nvidia: disagrees about version of symbol sme_me_mask
[26273.128894] nvidia: Unknown symbol sme_me_mask (err -22)

```
Any idea?

**Comment by SI-Abid** [comment]
> I was able to install and run the NVIDIA container with a **Ubuntu 24.04** host using the `nvidia/cuda:11.7.1-cudnn8-devel-ubuntu22.04` container.
> 
> ## Installation
> As said [@elezar](https://github.com/elezar) the documentation is: https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#linux-distributions
> 
> curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg \
>   && curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | \
>     sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
>     sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
> Update the packages list from the repository: `sudo apt-get update` Install the NVIDIA Container Toolkit packages: `sudo apt-get install -y nvidia-container-toolkit`
> 
> # Usage
> As before: `docker run --runtime nvidia -it nvidia/cuda:11.7.1-cudnn8-devel-ubuntu22.04 bash`

Thank you
