### ISSUE TITLE
Is that possible to use CUDA in the container without installing on host machine?

### ISSUE THREAD

**Issue by Pandede** [NVIDIA/nvidia-container-toolkit#487]
I mention that [NVIDIA GPU Operator](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/index.html) allows CUDA be used in container even the host machine does not install CUDA. Is that possible to do this in `nvidia-container-toolkit`?
Of course, the prerequirement is the container runs on the image [nvidia/cuda](https://hub.docker.com/r/nvidia/cuda/).

**Comment by elezar** [comment]
Does the information on installing and running workloads here https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/sample-workload.html provide the information that you need.

The `nvidia-container-toolkit` is the component used by the GPU Operator to add GPU support to containers. Assuming that the NVIDIA CUDA driver is installed, the `nvidia-container-toolkit` can be used to run GPU-enabled containers using runtimes such as Podman, Docker, Containerd, and Cri-o locally.

**Comment by Pandede** [comment]
@elezar Thanks for your quick reply. So, the minimum requirement is the NVIDIA CUDA driver is installed at the host machine?
I ask for it because the prerequisites in this [page](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#configuration) does not state that the NVIDIA CUDA driver MUST be installed at the host machine.

**Comment by elezar** [comment]
It is listed as the next steps: https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#next-steps

The driver is not a prerequisite to install and configure the toolkit, but is required to run things. Which is why this is listed before the "running a sample workload" section.

**Comment by Pandede** [comment]
Thank you, that's crystal clear. I may close the issue.
