### ISSUE TITLE
debian 12 support

### ISSUE THREAD

**Issue by St897** [NVIDIA/nvidia-container-toolkit#489]
Hello,

there are several issue with debian 12, this does not seem to work (properly):
* https://github.com/NVIDIA/nvidia-container-toolkit/issues?q=is%3Aissue+is%3Aopen+debian+12
  * many issues
* https://nvidia.github.io/nvidia-container-runtime/
  *  no 12, replaced by toolkit
* https://packages.debian.org/search?suite=all&section=all&arch=any&searchon=names&keywords=nvidia-container-toolkit
  * normal, not found
* https://nvidia.github.io/libnvidia-container/stable/deb/
  * no https://nvidia.github.io/libnvidia-container/stable/debian12/nvidia-container-toolkit.list
  * yes https://nvidia.github.io/libnvidia-container/stable/debian11/nvidia-container-toolkit.list

so i guess this unusable in debian 12?
while looking for the nvidia-ctk command

hth

**Comment by elezar** [comment]
@St897 do the packages rooted at https://nvidia.github.io/libnvidia-container/stable/deb/ not work for you?

The instructions at https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#installing-with-apt should work for all debian-based distributions.

**Comment by St897** [comment]
apt search/install/show does not find anything as https://nvidia.github.io/libnvidia-container/stable/debian12/nvidia-container-toolkit.list does not exist

**Comment by klueska** [comment]
We no longer have per-distro packages. The instructions Evan linked wshould work for any deb-package based distribution.

**Comment by St897** [comment]
> We no longer have per-distro packages. The instructions Evan linked should work for any deb-package based distribution.

ok, tnx, sounds weird? :) 

just to avoid confustion, then changing https://nvidia.github.io/libnvidia-container/stable/deb/ with this info should be usefull for anyone visiting the site

**Comment by elezar** [comment]
@St897 you're right. The text there has not been updated to reflect the stable repos that were released. We will update it.

**Comment by elezar** [comment]
I have updated the documentation. 

Let me know if there are still problems.
