### ISSUE TITLE
nvidia-ctk: symbol lookup error: nvidia-ctk: undefined symbol: nvmlGpuInstanceGetComputeInstanceProfileInfoV

### ISSUE THREAD

**Issue by atasoglou** [NVIDIA/nvidia-container-toolkit#49]
I cannot run nvidia docker containers. Error is related to `nvidia-ctk`.  If I just run `nvidia-ctk` I am getting the following error (which is the same reported by docker):
```
nvidia-ctk: symbol lookup error: nvidia-ctk: undefined symbol: nvmlGpuInstanceGetComputeInstanceProfileInfoV
```

Version info:
- nvidia-container-toolkit 1.12.0
- libnvidia-container 1.12.0
- libnvidia-container-tools 1.12.0
- NVIDIA Driver Version: 525.85.05
- nvidia-docker 2.12.0
- kernel version: 6.1.9-arch1-2

**Comment by klueska** [comment]
I could see how this might be possible if the `nvidia-ctk` binary was not built with:
```
go build -ldflags="-extldflags=-Wl,-z,lazy" ...
```
similar to https://github.com/NVIDIA/go-nvml/issues/18

@elezar can you confirm if we build  `nvidia-ctk` with these flags?

**Comment by elezar** [comment]
We do not (see https://gitlab.com/nvidia/container-toolkit/container-toolkit/-/blob/main/Makefile#L64):
```
	GOOS=$(GOOS) go build -ldflags "-s -w -X $(CLI_VERSION_PACKAGE).gitCommit=$(GIT_COMMIT) -X $(CLI_VERSION_PACKAGE).version=$(CLI_VERSION)" $(COMMAND_BUILD_OPTIONS) $(MODULE)/cmd/$(*)
```

I will create an MR to update these.

**Comment by atasoglou** [comment]
Hello @elezar. I just compiled your branch. It is working fine, thanks:
```
NAME:
   NVIDIA Container Toolkit CLI - Tools to configure the NVIDIA Container Toolkit

USAGE:
   nvidia-ctk [global options] command [command options] [arguments...]

VERSION:
   1.13.0-rc.1
commit: 1407ace94ab7c1501f311467fc74b96f4d966937

COMMANDS:
   hook     A collection of hooks that may be injected into an OCI spec
   runtime  A collection of runtime-related utilities for the NVIDIA Container Toolkit
   info     Provide information about the system
   cdi      Provide tools for interacting with Container Device Interface specifications
   system   A collection of system-related utilities for the NVIDIA Container Toolkit
   help, h  Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --debug, -d    Enable debug-level logging (default: false) [$NVIDIA_CTK_DEBUG]
   --help, -h     show help (default: false)
   --version, -v  print the version (default: false)
```

**Comment by elezar** [comment]
@atasoglou would a `1.13.0-rc.1` release work for your purposes, or is this a use case where a `1.12.1` patch release is required?

**Comment by atasoglou** [comment]
Yes a `1.13.0-rc.1` is definitely working for me, thanks. I also have the option to work with your branch in the meantime.

**Comment by elezar** [comment]
@atasoglou we have released `v1.13.0-rc.1` to our experimental repositories. This should include the fix.

**Comment by elezar** [comment]
This should have been addressed in both the `v1.12.1` and `v1.13.0` releases. 

Please reopen the issue if there is still a problem using either of these versions.

**Comment by enihcam** [comment]
this issue happens again:
```
/tmp/makepkg/nvidia-container-toolkit/pkg/nvidia-container-toolkit/usr/bin/nvidia-ctk: symbol lookup error: /tmp/makepkg/nvidia-container-toolkit/pkg/nvidia-container-toolkit/usr/bin/nvidia-ctk: undefined symbol: nvmlGpuInstanceGetComputeInstanceProfileInfoV
==> ERROR: A failure occurred in package().
    Aborting...
error: failed to build 'nvidia-container-toolkit-1.14.3-4': 
error: packages failed to build: nvidia-container-toolkit-1.14.3-4
```

**Comment by elezar** [comment]
@enihcam how are you building the packages? Are you including the relevant ldflags when building the executable?

**Comment by enihcam** [comment]
> @enihcam how are you building the packages? Are you including the relevant ldflags when building the executable?

using `lazy` flag resolves the issue. thanks.

**Comment by Dentrax** [comment]
Hey @elezar, I just hit this issue while building the new `v1.17` version: (even `lazy` is set)

```
$ git clone https://github.com/NVIDIA/nvidia-container-toolkit.git --depth 1
$ make cmds
go build -ldflags "-s -w '-extldflags=-Wl,--export-dynamic -Wl,--unresolved-symbols=ignore-in-object-files -Wl,-z,lazy' -X github.com/NVIDIA/nvidia-container-toolkit/internal/info.gitCommit=1995925a7df644ead7afb767608841d9a08bcbc4 -X github.com/NVIDIA/nvidia-container-toolkit/internal/info.version=1.17.0"  github.com/NVIDIA/nvidia-container-toolkit/cmd/nvidia-cdi-hook
$ ./nvidia-cdi-hook -v
./nvidia-cdi-hook: symbol lookup error: ./nvidia-cdi-hook: undefined symbol: nvmlGpuInstanceGetComputeInstanceProfileInfoV
```

Do you have any thoughts on this? 🤔 What I'm missing?

**Comment by developer-guy** [comment]
I'm also hitting the same issue, are there any updates, kindly ping @elezar? Thank you.
