### ISSUE TITLE
Unable to Run nvidia-smi, but CUDA Accessible for Other Applications (e.g., PyTorch)

### ISSUE THREAD

**Issue by SevenFo** [NVIDIA/nvidia-container-toolkit#498]
When running `docker run --rm -it --gpus all ubuntu nvidia-smi`, the output indicates a missing file or directory: `/usr/bin/nvidia-smi: line 4: /usr/bin/.nvidia-smi: No such file or directory`. 

Upon entering the container and examining `/usr/bin/nvidia-smi`, it appears as a bash script:

```
root@4b218781f03b:/# cat /usr/bin/nvidia-smi
#!/bin/bash

if [ $# -eq 0 ]; then
  /usr/bin/.nvidia-smi | grep -v python2.8
else
  /usr/bin/.nvidia-smi "$@"
fi
```

It's peculiar that `nvidia-smi` is represented as a bash script rather than a binary file within the Docker container.

Although encountering issues with running nvidia-smi within the Docker container, PyTorch functions properly with CUDA. For instance, `torch.cuda.is_available()` returns True, indicating CUDA accessibility.

Other information
```
$ nvidia-container-runtime -v
runc version 1.1.12
commit: v1.1.12-0-g51d5e94
spec: 1.0.2-dev
go: go1.21.9
libseccomp: 2.5.3

$ nvidia-container-cli -V
cli-version: 1.15.0
lib-version: 1.15.0
build date: 2024-04-15T13:36+00:00
build revision: 6c8f1df7fd32cea3280cf2a2c6e931c9b3132465
build compiler: x86_64-linux-gnu-gcc-7 7.5.0
build platform: x86_64
build flags: -D_GNU_SOURCE -D_FORTIFY_SOURCE=2 -DNDEBUG -std=gnu11 -O2 -g -fdata-sections -ffunction-sections -fplan9-extensions -fstack-protector -fno-strict-aliasing -fvisibility=hidden -Wall -Wextra -Wcast-align -Wpointer-arith -Wmissing-prototypes -Wnonnull -Wwrite-strings -Wlogical-op -Wformat=2 -Wmissing-format-attribute -Winit-self -Wshadow -Wstrict-prototypes -Wunreachable-code -Wconversion -Wsign-conversion -Wno-unknown-warning-option -Wno-format-extra-args -Wno-gnu-alignof-expression -Wl,-zrelro -Wl,-znow -Wl,-zdefs -Wl,--gc-sections
```

**Comment by klueska** [comment]
nvidia-smi is injected from your host. This means that, on your host, you (or someone) must have created a wrapper around nvidia-smi as a bash script. You will manually need to inject the `/usr/bin/.nvidia-smi` file that is referenced if you want to get this to work.

**Comment by SevenFo** [comment]
> Refer

Thank you! I got it, I need to rename `/usr/bin/.nvidia-smi` back to `/usr/bin/nvidia-smi`
