### ISSUE TITLE
nvidia-docker.list url not available for ubuntu 24.04

### ISSUE THREAD

**Issue by lennard-pfennig-bruker** [NVIDIA/nvidia-container-toolkit#565]
The url https://nvidia.github.io/nvidia-docker/ubuntu24.04/nvidia-docker.list results in 

> Unsupported distribution! # Check https://nvidia.github.io/nvidia-docker

I used the url for ubuntu 20 and 22 from a generic script in my pipelines, which are not working now. Is this not supported anymore? I am happy to adapt, just want to do it correctly

Edit:
Following the updated instructions from the [official docs](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/1.13.5/install-guide.html#step-2-install-nvidia-container-toolkit) I found out that this 
 url https://nvidia.github.io/libnvidia-container/ubuntu24.04/libnvidia-container.list also results in 

> Unsupported distribution or misconfigured repository settings

for now I am using the generic url https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list which seems to work fine

**Comment by elezar** [comment]
@lennard-pfennig-bruker using the generic URL (https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list) is recommended for all Ubuntu versions since 18.04.

Maintaining explicit copies for each supported distribution was not scaling well.

**Comment by lennard-pfennig-bruker** [comment]
thanks

**Comment by rabyunghwa** [comment]
@elezar What about Ubuntu 16.04? Which URL should I use?
