### ISSUE TITLE
How to install NVIDIA Container toolkit

### ISSUE THREAD

**Issue by kawasaki94year** [NVIDIA/nvidia-container-toolkit#603]
Hello,Everyone:
  I have a problem that I encountered while using the [NVIDIA Container Toolkit guid](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#installation) to install the NVIDIA Container Toolkit,There is an Issue when I follow the instructions on Ubuntu 22.04 WSL:

>  `curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg \
&& curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | \
sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list`

> `The file ‘/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg’ already exists. Do you want to overwrite it? (y/N) curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to nvidia.github.io:443
y
gpg: No valid OpenPGP data found.`

I found a solution online that visit the [ website](https://github.io.ipaddress.com/) to look up the IP address of nvidia.github.io, Then Run the command `sudo vim /etc/hosts` and add the following content at the end of the file:
`185.199.108.153 nvidia.github.io
185.199.109.153 nvidia.github.io
185.199.110.153 nvidia.github.io
185.199.111.153 nvidia.github.io`
Finally, follow the official steps for installation. but this method doesn't seem to be effective. So what could be the reason for this? Are there any other methods for installation?

**Comment by kawasaki94year** [comment]
If you encounter the above issue, you need to change the image source:
`sudo apt-get update
sudo apt-get install \
    ca-certificates \
    curl \
    gnupg \
    lsb-release
`
`curl -fsSL https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
`
`echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/ubuntu \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
`
`curl -fsSL https://mirrors.ustc.edu.cn/docker-ce/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
`
`echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://mirrors.ustc.edu.cn/docker-ce/linux/ubuntu \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
`
`sudo apt-get update
sudo apt-get install docker-ce docker-ce-cli containerd.io
`
`sudo systemctl start docker
sudo systemctl enable docker
`
`sudo docker run hello-world
`
`curl -fsSL https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/ubuntu \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

sudo apt-get update
sudo apt-get install docker-ce docker-ce-cli containerd.io
`
`distribution=$(. /etc/os-release;echo $ID$VERSION_ID) && \
curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add - && \
curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | \
sed 's#https://#https://mirrors.tuna.tsinghua.edu.cn/#g' | sudo tee /etc/apt/sources.list.d/nvidia-docker.list

sudo apt-get update
sudo apt-get install -y nvidia-docker2
sudo systemctl restart docker
`
`sudo docker run --gpus all --rm nvidia/cuda:10.0-base nvidia-smi
`
`# Docker 阿里云源
sudo mkdir -p /etc/systemd/system/docker.service.d
sudo tee /etc/docker/daemon.json <<-'EOF'
{
  "registry-mirrors": ["https://<your-mirror-id>.mirror.aliyuncs.com"]
}
EOF
sudo systemctl daemon-reload
sudo systemctl restart docker

# NVIDIA Docker 阿里云源
distribution=$(. /etc/os-release;echo $ID$VERSION_ID) && \
curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add - && \
curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | \
sed 's#https://#https://mirrors.aliyun.com/#g' | sudo tee /etc/apt/sources.list.d/nvidia-docker.list

sudo apt-get update
sudo apt-get install -y nvidia-docker2
sudo systemctl restart docker
`

**Comment by kawasaki94year** [comment]
Docker:
`sudo apt-get update
`
`sudo apt-get install apt-transport-https ca-certificates curl  gnupg lsb-release`

**Comment by dfengpo** [comment]
请问楼主是否解决了

**Comment by kawasaki94year** [comment]
> 请问楼主是否解决了

已经解决了，需要更换源

**Comment by aodexiusi1997** [comment]
> > 请问楼主是否解决了
> 
> 已经解决了，需要更换源

请问添加的是什么源，请问一下

**Comment by kawasaki94year** [comment]
> > > 请问楼主是否解决了
> > 
> > 已经解决了，需要更换源
> 
> 请问添加的是什么源，请问一下

我添加的是清华镜像的源，只是有时候不太稳定，要多试几次

**Comment by kawasaki94year** [comment]
> 请问有源的链接吗，我现在的已经是清华源了，但是从来没有成功过

用这个试试，我是搭梯子在加上这个：curl -fsSL https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

**Comment by aodexiusi1997** [comment]
> > 请问有源的链接吗，我现在的已经是清华源了，但是从来没有成功过
> 
> 用这个试试，我是搭梯子在加上这个：curl -fsSL https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

我也成功了，用的手机usb共享热点安装好了这个gpg，公司的网就装不了

**Comment by dfengpo** [comment]
最后 install NVIDIA Container toolkit  能成功吗，我用的是云服务器，没法切换网络，但是服务器上已经可以翻墙的，还是一直报找不到源的问题

**Comment by aodexiusi1997** [comment]
> 最后 install NVIDIA Container toolkit 能成功吗，我用的是云服务器，没法切换网络，但是服务器上已经可以翻墙的，还是一直报找不到源的问题

最后成功了。不知道是啥玄学问题。试试上面换成清华源

**Comment by dfengpo** [comment]
我执行
distribution=$(. /etc/os-release;echo $ID$VERSION_ID) &&
curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add - &&
curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list |
sed 's#https://#https://mirrors.aliyun.com/#g' | sudo tee /etc/apt/sources.list.d/nvidia-docker.list


报gpg: 找不到有效的 OpenPGP 数据
这个错，还是无法成功

**Comment by kawasaki94year** [comment]
> 我执行 distribution=$(. /etc/os-release;echo $ID$VERSION_ID) && curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add - && curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sed 's#https://#https://mirrors.aliyun.com/#g' | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
> 
> 报gpg: 找不到有效的 OpenPGP 数据
> 
> apt-get install -y nvidia-docker2 这句也是报Unable to locate package nvidia-docker2
> 
> 这个错，还是无法成功

试试这个链接里面的步骤，上次我是综合了这两个步骤就可以了，[https://blog.csdn.net/Yonggie/article/details/140460258](url)

**Comment by dfengpo** [comment]
见证奇迹的时刻发生了，竟然安装成功,非常感谢楼主
![image](https://github.com/user-attachments/assets/9572f3aa-4f9f-44c3-8d29-fbf81e3d2250)

**Comment by kawasaki94year** [comment]
> 见证奇迹的时刻发生了，竟然安装成功,非常感谢楼主 ![image](https://private-user-images.githubusercontent.com/12029452/357882047-9572f3aa-4f9f-44c3-8d29-fbf81e3d2250.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2NDg4OTIsIm5iZiI6MTcyMzY0ODU5MiwicGF0aCI6Ii8xMjAyOTQ1Mi8zNTc4ODIwNDctOTU3MmYzYWEtNGY5Zi00NGMzLThkMjktZmJmODFlM2QyMjUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDE1MTYzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1ODUyNmJiZmUyYzdmNTA5MzU2MDMxMjBjNmUyYTMxMWQwZDY5NGQ2MGUyZTg2OGQ0YTQwZWVkNmU0NDI0YzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TDe0AZuwKVG67QomFdLTAJnFBh0B7Z15g7t2GCbntpQ)

没关系，后续有时间，我重新整理一下过程，前面的过程写的比较乱。

**Comment by kawasaki94year** [comment]
> Docker:
> 
> 1. `sudo apt-get update`
> 2. `sudo apt-get install apt-transport-https ca-certificates curl  gnupg lsb-release`
> 3. `curl -fsSL https://mirrors.aliyun.com/docker-ce/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg`
> 4. `echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://mirrors.aliyun.com/docker-ce/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null`
> 5. `sudo apt-get update`
> 6. `sudo apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin`
> 7. `sudo systemctl enable docker`
> 8. `sudo systemctl start docker`
> 9. `sudo groupadd docker`
> 10. `sudo usermod -aG docker $USER`
> 11. `docker run --rm hello-world`

If you see the message "gpg: No valid OpenPGP data found," you'll need to break down the installation steps from the official website as follows:

1. In your web browser, navigate [to:]( https://nvidia.github.io/libnvidia-container/gpgkey ) and download the GPG file, saving it to your desktop.
2. Run the command:`cat gpgkey_path | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg`，where` gpgkey_path` should be replaced with the path to your downloaded GPG file. For example: `/home/XWL/filename`.
3. Similarly to the GPG installation process, [visit:]( https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list)，and you should see the following:
```
deb https://nvidia.github.io/libnvidia-container/stable/deb/$(ARCH) /
#deb https://nvidia.github.io/libnvidia-container/experimental/deb/$(ARCH) /
```
4. Use the `touch` command to create a file named `nvidia-container-toolkit.list`. Copy and paste the content from step 3 into this newly created file, then save and exit.
5. Run the following command:
```
cat /home/XWanL/nvidia-container-toolkit.list | \
sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
```
6. Execute `sudo apt-get update`.
7. Finally, run `sudo apt-get install -y nvidia-container-toolkit`.

**Comment by dfengpo** [comment]
good

**Comment by wzystal** [comment]
> 见证奇迹的时刻发生了，竟然安装成功,非常感谢楼主 ![image](https://github.com/user-attachments/assets/9572f3aa-4f9f-44c3-8d29-fbf81e3d2250)

老哥你好，我也遇到了跟你一样的问题，前面步骤都ok的，但是安装的时候都提示找不到包：
E: Unable to locate package nvidia-container-toolkit
E: Unable to locate package nvidia-container-runtime

E: Unable to locate package nvidia-docker2

想问下你后面是怎么突然就成功了呀？

**Comment by kawasaki94year** [comment]
> > Docker:
> > 
> > 1. `sudo apt-get update`
> > 2. `sudo apt-get install apt-transport-https ca-certificates curl  gnupg lsb-release`
> > 3. `curl -fsSL https://mirrors.aliyun.com/docker-ce/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg`
> > 4. `echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://mirrors.aliyun.com/docker-ce/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null`
> > 5. `sudo apt-get update`
> > 6. `sudo apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin`
> > 7. `sudo systemctl enable docker`
> > 8. `sudo systemctl start docker`
> > 9. `sudo groupadd docker`
> > 10. `sudo usermod -aG docker $USER`
> > 11. `docker run --rm hello-world`
> 
> If you see the message "gpg: No valid OpenPGP data found," you'll need to break down the installation steps from the official website as follows:
> 
> 1. In your web browser, navigate [gpgkey](https://nvidia.github.io/libnvidia-container/gpgkey) and download the GPG file, saving it to your desktop.
> 2. Run the command:`cat gpgkey_path | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg`，where` gpgkey_path` should be replaced with the path to your downloaded GPG file. For example: `/home/XWL/filename`.
> 3. Similarly to the GPG installation process, [nvidia-container-toolkit.list](https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list)，and you should see the following:
> 
> ```
> deb https://nvidia.github.io/libnvidia-container/stable/deb/$(ARCH) /
> #deb https://nvidia.github.io/libnvidia-container/experimental/deb/$(ARCH) /
> ```
> 
> 4. Use the `touch` command to create a file named `nvidia-container-toolkit.list`. Copy and paste the content from step 3 into this newly created file, then save and exit.
> 5. Run the following command:
> 
> ```
> cat /home/XWanL/nvidia-container-toolkit.list | \
> sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
> sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
> ```
> 
> 6. Execute `sudo apt-get update`.
> 7. Finally, run `sudo apt-get install -y nvidia-container-toolkit`.

@wzystal 试试这个步骤

**Comment by popcion** [comment]
一样，按上面步骤做了
E: Unable to locate package nvidia-container-toolkit

**Comment by Ko24Bewjw** [comment]
> 一样，按上面步骤做了 E: Unable to locate package nvidia-container-toolkit

你好，这个问题请问你解决了吗 @popcion

**Comment by popcion** [comment]
> 你好，这个问题请问你解决了吗 [@popcion](https://github.com/popcion)
不好意思，印象中并没有解决

**Comment by kawasaki94year** [comment]
> > > Docker:
> > > 
> > > 1. `sudo apt-get update`
> > > 2. `sudo apt-get install apt-transport-https ca-certificates curl  gnupg lsb-release`
> > > 3. `curl -fsSL https://mirrors.aliyun.com/docker-ce/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg`
> > > 4. `echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://mirrors.aliyun.com/docker-ce/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null`
> > > 5. `sudo apt-get update`
> > > 6. `sudo apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin`
> > > 7. `sudo systemctl enable docker`
> > > 8. `sudo systemctl start docker`
> > > 9. `sudo groupadd docker`
> > > 10. `sudo usermod -aG docker $USER`
> > > 11. `docker run --rm hello-world`
> > 
> > 
> > If you see the message "gpg: No valid OpenPGP data found," you'll need to break down the installation steps from the official website as follows:
> > 
> > 1. In your web browser, navigate [gpgkey](https://nvidia.github.io/libnvidia-container/gpgkey) and download the GPG file, saving it to your desktop.
> > 2. Run the command:`cat gpgkey_path | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg`，where` gpgkey_path` should be replaced with the path to your downloaded GPG file. For example: `/home/XWL/filename`.
> > 3. Similarly to the GPG installation process, [nvidia-container-toolkit.list](https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list)，and you should see the following:
> > 
> > ```
> > deb https://nvidia.github.io/libnvidia-container/stable/deb/$(ARCH) /
> > #deb https://nvidia.github.io/libnvidia-container/experimental/deb/$(ARCH) /
> > ```
> > 
> > 
> >     
> >   
> > 
> > 4. Use the `touch` command to create a file named `nvidia-container-toolkit.list`. Copy and paste the content from step 3 into this newly created file, then save and exit.
> > 5. Run the following command:
> > 
> > ```
> > cat /home/XWanL/nvidia-container-toolkit.list | \
> > sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
> > sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
> > ```
> > 
> > 
> >     
> >   
> > 
> > 6. Execute `sudo apt-get update`.
> > 7. Finally, run `sudo apt-get install -y nvidia-container-toolkit`.
> 
> [@wzystal](https://github.com/wzystal) 试试这个步骤

**Comment by kawasaki94year** [comment]
> > 你好，这个问题请问你解决了吗 [@popcion](https://github.com/popcion)
> 
> 不好意思，印象中并没有解决

试试这个呢：[https://github.com/NVIDIA/nvidia-container-toolkit/issues/603#issuecomment-2350918061](url)

**Comment by kawasaki94year** [comment]
> > 一样，按上面步骤做了 E: Unable to locate package nvidia-container-toolkit
> 
> 你好，这个问题请问你解决了吗 [@popcion](https://github.com/popcion)

可能是源和Gpg的问题

**Comment by minhanghuang** [comment]
```shell
curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey \   | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg

ooooorrrrrrrr
ooooorrrrrrrr

# curl -fsSL http://你的代理:端口 https://nvidia.github.io/libnvidia-container/gpgkey \   | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
```

```shell
curl -s -L https://mirrors.aliyun.com/libnvidia-container/stable/deb/nvidia-container-toolkit.list | \
    sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
    sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
```


```shell
sed -i -e '/experimental/ s/^#//g' /etc/apt/sources.list.d/nvidia-container-toolkit.list
```

```shell
sudo sed -i 's/nvidia.github.io/mirrors.aliyun.com/g' /etc/apt/sources.list.d/nvidia-container-toolkit.list
```

```shell
sudo apt update && sudo apt install -y nvidia-container-toolkit
```
