### ISSUE TITLE
Missing libnvidia-container 1.16.0 release

### ISSUE THREAD

**Issue by lahwaacz** [NVIDIA/nvidia-container-toolkit#613]
The [v1.16.0 release notes](https://github.com/NVIDIA/nvidia-container-toolkit/releases/tag/v1.16.0) have a link to [libnvidia-container 1.16.0](https://github.com/NVIDIA/libnvidia-container/releases/tag/v1.16.0) which does not exist.

**Comment by lahwaacz** [comment]
Also why was the latest release made by github-actions rather than @elezar?

**Comment by lahwaacz** [comment]
@elezar After [v1.16.1](https://github.com/NVIDIA/nvidia-container-toolkit/releases/tag/v1.16.1) there is still not libnvidia-container release, what's the holdup?

**Comment by lahwaacz** [comment]
cc @cdesiniotis

**Comment by klueska** [comment]
It looks like the artifacts were produced, but the tag / github release were not created:
https://github.com/NVIDIA/libnvidia-container/tree/gh-pages/stable/deb
https://github.com/NVIDIA/libnvidia-container/tree/gh-pages/stable/rpm
https://github.com/NVIDIA/libnvidia-container/tree/gh-pages/stable/centos8

/cc @ArangoGutierrez as @elezar is out on PTO.

**Comment by lahwaacz** [comment]
@cdesiniotis @klueska @ArangoGutierrez @elezar Can you address this issue finally? It is blocking the packaging process of nvidia-container-toolkit for Arch Linux where we assume that libnvidia-container and nvidia-container-toolkit are released in tandem and their version numbers always match. If this is not true anymore, I'd expect a statement on the new release process; otherwise just make a new libnvidia-container release.

**Comment by elezar** [comment]
@lahwaacz sorry for the delay. We have been working on improving our release tooling and missed this in our transistion. I have created the relevant releases.

**Comment by lahwaacz** [comment]
@elezar Thanks, I was able to release the packages for Arch Linux now :tada:
