### ISSUE TITLE
`nvidia-container-runtime-hook` binary location should prefer toolkit install directory

### ISSUE THREAD

**Issue by chiragjn** [NVIDIA/nvidia-container-toolkit#64]
I stumbled upon this on aws eks nodes after setting up the toolkit via `gpu-operator` and trying to get devices working via `volume-mounts`

After installing `nvidia-container-toolkit:v1.13.1` via `gpu-operator:v23.3.1`
and running it with the following environment variables
```
ACCEPT_NVIDIA_VISIBLE_DEVICES_ENVVAR_WHEN_UNPRIVILEGED="false"
ACCEPT_NVIDIA_VISIBLE_DEVICES_AS_VOLUME_MOUNTS="true"
```

I am using `containerd` as low-level runtime and `nvidia` as the CRI runtime. 
It correctly updates the `etc/containerd/config.toml` to use `nvidia` as the runtime. 
Further, it also installs all the runtimes and hook binaries in `/usr/local/nvidia/toolkit` (the default for `nvidia-toolkit install`) with the `nvidia-container-runtime-hook` file correctly wrapping the `nvidia-container-runtime-hook.real` with the right config.toml

However, when the runtime is invoked, it has no idea where the toolkit was installed and instead, it relies on `PATH` or well known paths to look for the binary

https://github.com/NVIDIA/nvidia-container-toolkit/blob/dc6a895db8e75740e51973140539d6c04f4f580a/internal/modifier/stable.go#L57

Unfortunately, on EKS gpu nodes come with `nvidia-container-runtime-hook` and `nvidia-container-cli` pre-installed in `/usr/bin` and this hook binary has no idea about the custom config.toml

For this to work, my node needs to have `/usr/local/nvidia/toolkit` earliest in `PATH` which I am not sure is possible.

If I understand the code correctly, it should be possible to add the path `/usr/local/nvidia/toolkit/nvidia-container-runtime-hook` to `RuntimeHookConfig`?

https://github.com/NVIDIA/nvidia-container-toolkit/blob/dc6a895db8e75740e51973140539d6c04f4f580a/internal/config/hook.go#L20

which can then be passed along to the legacy runtime constructor

https://github.com/NVIDIA/nvidia-container-toolkit/blob/dc6a895db8e75740e51973140539d6c04f4f580a/internal/runtime/runtime_factory.go#L93-L96

**Comment by elezar** [comment]
Hi @chiragjn. You're right in pointing out that the `nvidia-container-runtime-hook` on the path will be used. This also means that if you apply your workaround of ensuring that `/usr/local/nvidia/toolkit` is earlier in the path will also affect containers run using the NVIDIA Container Runtime installed on the host.

I think adding an `nvidia-container-runtime-hook.path` option to the config file would be feasible on our end, meaning that we can handle this in the same way that we handle `nvidia-ctk` at the moment.

We are working on the 1.14.0 release which should be out by the end of June, since the changes are small, we should be able to get them in by then.

**Comment by elezar** [comment]
cc @cdesiniotis @shivamerla

**Comment by chiragjn** [comment]
Started a PR for this: #65 :) 
Let me know if it would be helpful for me to continue working on the tests

**Comment by elezar** [comment]
Thanks for the PR! I will have a look.

Note that I also created https://gitlab.com/nvidia/container-toolkit/container-toolkit/-/merge_requests/401 with the proposed changes. Feel free to extend that with additional tests, or give feedback there if something isn't working as expected.

**Comment by chiragjn** [comment]
Awesome! didn't realise the main source was on Gitlab 😅 
Seems like you guys have made all the required changes
Thanks a lot 🙌

**Comment by elezar** [comment]
@chiragjn yes, we are aware of the issues with EKS and having the NVIDIA Container Toolkit already configured. @cdesiniotis do you have a link to the docs that we released to address this issue?

**Comment by chiragjn** [comment]
```
containerd --version
containerd github.com/containerd/containerd 1.6.19 1e1ea6e986c6c86565bc33d52e34b81b3e2bc71f
```

The AMI is using version 1 config

```
root = "/var/lib/containerd"
state = "/run/containerd"
version = 1
```

I'll have to read how to switch to version 2 or raise a request with https://github.com/awslabs/amazon-eks-ami

**Comment by cdesiniotis** [comment]
Hi @chiragjn here is our documentation for EKS: https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/amazon-eks.html. We have only tested two deployment options, 1) using the preinstalled driver + toolkit in the EKS AMI, and 2) bringing your own AMI and depending on gpu-operator (recommended).

**Comment by chiragjn** [comment]
Got it, thanks! It would have been better if there was a breaking change and 

```
ACCEPT_NVIDIA_VISIBLE_DEVICES_ENVVAR_WHEN_UNPRIVILEGED="false"
ACCEPT_NVIDIA_VISIBLE_DEVICES_AS_VOLUME_MOUNTS="true"
```

were made the defaults. It is baffling that everyone's GPU isolation is by default broken because of backward compatibility. Anyway, thanks again for the help and fixes

**Comment by chiragjn** [comment]
I am closing this now because newer version of toolkit addresses the reported problem at least. I have managed to hack the containerd config to get my main issue resolved
