### ISSUE TITLE
support for ubuntu 21.10

### ISSUE THREAD

**Issue by armando-fandango** [NVIDIA/nvidia-container-toolkit#7]
please add support for ubuntu 21.10

**Comment by elezar** [comment]
Hi @armando-fandango. We don't specifically support non-LTS releases. With that said, the Ubuntu 18.04 packages should be usable on all later Ubuntu distributions.

Please follow the instructions [here](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#setting-up-nvidia-container-toolkit), specifying `ubuntu18.04` as your `$distribution`.

**Comment by lemmyg** [comment]
Hello,
I tried with $distribution=ubuntu18.04 and 20.04 with both I get same error in ubuntu 21.10.
sudo docker run --rm --gpus all nvidia/cuda:11.0-base nvidia-smi
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: container error: cgroup subsystem devices not found: unknown.

thanks

**Comment by elezar** [comment]
@lemmyg the issue here is that ubuntu 21.10 uses cgroupv2 by default. This can either be disabled, or you could try the `1.8.0-rc.1` release of the NVIDIA Container Toolkit which includes support for cgroupv2 (see https://github.com/NVIDIA/libnvidia-container/issues/111#issuecomment-989024375).

There are some bugs that we're still ironing out and will be publishing an `rc.2` soon.

**Comment by lemmyg** [comment]
thanks for you quick reply. that works :)
it would be great if you could add the note about the cgroupv2 issue in the installation guide
https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#docker
thanks again! :)

**Comment by klueska** [comment]
`libnvidia-container-1.8.0-rc.2` is now live with some minor updates to fix some edge cases around `cgroupv2` support.

Please see NVIDIA/libnvidia-container#111 (comment) for instructions on how to get access to this RC (or wait for the full release at the end of next week).

**Note:** This does not directly add `ubuntu21.10` support, but you can point to the `ubuntu20.04` repo and install from there for now.

**Comment by lemmyg** [comment]
Awesome!

**Comment by klueska** [comment]
`libnvidia-container-1.8.0` with `cgroupv2` support is now GA

Release notes here:
https://github.com/NVIDIA/libnvidia-container/releases/tag/v1.8.0

**Comment by klueska** [comment]
As Evan said, we don't (specifically) support non-LTS releases, but you should be able to do what Evan suggested here to get things to work: https://github.com/NVIDIA/nvidia-container-toolkit/issues/7#issuecomment-1014296629
