### ISSUE TITLE
curl error when adding GPG keyring on WSL2-Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by zgjja** [NVIDIA/nvidia-container-toolkit#76]
when using
```
curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
```
on **WSL2-Ubuntu22**, cause error:
```
curl: (35) error:0A000126:SSL routines::unexpected eof while reading.
gpg: no valid OpenPGP data found.
```
while that command **runs successfully on WSL2-Ubuntu20**.

Reference: [https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html)

**Comment by zgjja** [comment]
solved, it is the problem with proxy config on docker...

**Comment by StephennFernandes** [comment]
@zgjja facing similar issue. could you please elaborate your solution
