### ISSUE TITLE
nvidia docker

### ISSUE THREAD

**Issue by Bnn6** [NVIDIA/nvidia-container-toolkit#779]
nvidia-docker import --change "ENV NVIDIA_VISIBLE_DEVICES=all"
--change "ENV NVIDIA_DRIVER_CAPABILITIES=all" pwmat_gpu.tar pwmat:gpu
What command does this old version of the command correspond to in the current nvidia container toolkit?

**Comment by elezar** [comment]
nvidia-docker was a wrapper for docker, so you should be able to replace it with `docker` in the command you use

**Comment by Bnn6** [comment]
It works,thank you.

**Comment by Bnn6** [comment]
It works,thank you.
