### ISSUE TITLE
When I use containerd and CDI, I don't need to change the runtime of containerd to nvidia?

### ISSUE THREAD

**Issue by j2gg0s** [NVIDIA/nvidia-container-toolkit#79]
As a GPU newbee, I'm not sure if my understanding is correct.

The related document: https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#container-device-interface-cdi-support

**Comment by elezar** [comment]
@j2gg0s yes, that is correct. If the CDI mode in Containerd is used, then the NVIDIA Container Runtime is not used. Note that the `nvidia-ctk` CLI is still recommended as the mechanism for generating the CDI specifications for the available devices on the system. (This can be installed using the `nvidia-container-toolkit-base` packages for all supported distributions).
