### ISSUE TITLE
Cooperative Launch support?

### ISSUE THREAD

**Issue by WarShoe** [NVIDIA/nvidia-container-toolkit#8]
When I run my app in the docker container, I get:
`Cooperative Launch is not supported on this machine configuration.`

The installed package is `nvidia-container-toolkit_1.7.0-1_amd64.deb`, with 

```
# cat /etc/docker/daemon.json 
{
    "runtimes": {
        "nvidia": {
            "path": "/usr/bin/nvidia-container-runtime",
            "runtimeArgs": []
        }
    }
}
```

My GPU is correctly detected:
```
$ docker run --gpus all nvidia/cuda:11.0-base nvidia-smi -L
GPU 0: NVIDIA GeForce RTX 2060 SUPER (UUID: GPU-1d001a80-c8f0-e4ff-0f67-97aa13860315)
```

Is _Cooperative Launch_ supported in cuda-docker?! If YES, what do I miss?

Thanks a lot in advance!

**Comment by elezar** [comment]
Is this related to https://stackoverflow.com/questions/64960465/cuda-cudalaunchcooperativekernel-and-grid-synchronization?

(Does the example application work on the host?)

**Comment by WarShoe** [comment]
My application works correctly on the host (without docker).

**Comment by elezar** [comment]
Could you provide steps to reproduce?

**Comment by WarShoe** [comment]
I updated the system (including nvidia-container-runtime), and the docker image runs fine now.
