### ISSUE TITLE
Attempting to run nvidia-container-runtime returns  nvidia-container-cli.ldconfig value "/usr/sbin/ldconfig" is not host-relative (does not start with a '@') error

### ISSUE THREAD

**Issue by BRTPOB** [NVIDIA/nvidia-container-toolkit#830]
As the title says, when trying to run the nvidia-container-runtime, the command will return the following error:

`ERRO[0000] error loading config: nvidia-container-cli.ldconfig value "/usr/sbin/ldconfig" is not host-relative (does not start with a '@')
invalid config value`

This came up because my Plex and Jellyfin containers, that I was previously using to access my video card for hardware transcoding, fail with the following error:

`ERROR: for plex  Cannot start service plex: failed to create shim task: OCI runtime create failed: unable to retrieve OCI runtime error (open /run/containerd/io.containerd.runtime.v2.task/moby/a5ba468b6173006778af9210677a89a0fbdc50f2d506e9cd86cbbed77b191aca/log.json: no such file or directory): nvidia-container-runtime did not terminate successfully: exit status 1: unknown`

`ERROR: for plex  Cannot start service plex: failed to create shim task: OCI runtime create failed: unable to retrieve OCI runtime error (open /run/containerd/io.containerd.runtime.v2.task/moby/a5ba468b6173006778af9210677a89a0fbdc50f2d506e9cd86cbbed77b191aca/log.json: no such file or directory): nvidia-container-runtime did not terminate successfully: exit status 1: unknown
ERROR: Encountered errors while bringing up the project.`

These errors are new to the most recent container-toolkit upgrade. Running on Ubuntu 22.04.5 LTS prior to upgrading to 24.04.1 LTS as part of the troubleshooting process.

**Comment by cdesiniotis** [comment]
@BRTPOB the latest release of NVIDIA Container Toolkit was updated to not allow container-relative paths for the ldconfig binary by default. An `allow-ldconfig-from-container` feature flag was added to allow for this default behavior to be changed. If required for your environment, you can enable this feature flag by running: 
```
sudo nvidia-ctk config --in-place --set features.allow-ldconfig-from-container=true 
```

Refer to https://github.com/NVIDIA/nvidia-container-toolkit/pull/690

**Comment by BRTPOB** [comment]
Thanks, I had found the PR/issue related to that, and I was guessing it was due to that but wasn't sure.

The command fixed my issue, so again thanks for the info.
