### ISSUE TITLE
missing Release file for stable/ubuntu22.04/amd64

### ISSUE THREAD

**Issue by asabaini** [NVIDIA/nvidia-container-toolkit#89]
Hello, when I run `apt update` on my Ubuntu 22.04 host I get the following error

```bash
E: The repository 'https://nvidia.github.io/libnvidia-container/stable/ubuntu22.04/amd64  Release' no longer has a Release file
```

Looking forward to hearing from you
Best
Alberto

**Comment by elezar** [comment]
@asabaini it seems that you have manually edited your `.list` file to refer to `ubuntu22.04`. 

Please update this to refer to `ubuntu18.04` instead as in https://github.com/NVIDIA/libnvidia-container/blob/gh-pages/stable/ubuntu18.04/nvidia-container-toolkit.list

```
deb https://nvidia.github.io/libnvidia-container/stable/ubuntu18.04/$(ARCH) /
#deb https://nvidia.github.io/libnvidia-container/experimental/deb/$(ARCH) /
#deb https://nvidia.github.io/libnvidia-container/experimental/ubuntu18.04/$(ARCH) /
```

**Comment by asabaini** [comment]
Hello @elezar , thank you so much for your quick reply. My `.list` file looks like this

```
deb https://nvidia.github.io/libnvidia-container/stable/ubuntu22.04/$(ARCH) /
deb https://nvidia.github.io/nvidia-container-runtime/ubuntu22.04/$(ARCH) /
deb https://nvidia.github.io/nvidia-docker/ubuntu22.04/$(ARCH) /
```

I just put the output of `apt update` that I think replaced the variable

**Comment by asabaini** [comment]
Oh never mind, I see what you are saying now. It seems to be working now. Thank you for your help

**Comment by itsthejb** [comment]
Thanks for this, and I've now resolved the issue. However there will be a lot of people with this issue, since this change has broken alignment with the docs, e.g. https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html

**Comment by elezar** [comment]
> Thanks for this, and I've now resolved the issue. However there will be a lot of people with this issue, since this change has broken alignment with the docs, e.g. https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html

I wil be sure to update the documentation.

**Comment by tardis89** [comment]
Switching it to 18.04 fixed the issue for me too.

I also followed the documentation, and it is correct now so that it switches it to 18.04 when following the official directions in the guide link above.

**Comment by chschulze** [comment]
But why is there only a repo for an EOL Ubuntu, while it was working before? Pointing a 22.04 Ubuntu towards a 18.04 repo doesn't feel correct and likely will cause a lot of confusion for users.

**Comment by elezar** [comment]
> But why is there only a repo for an EOL Ubuntu, while it was there for the current Ubuntu versions before? Pointing a 22.04 Ubuntu towards a 18.04 repo doesn't feel correct and likely will cause a lot of confusion for users. Especially since these are (still?) valid: https://nvidia.github.io/nvidia-container-runtime/stable/ubuntu22.04/$(ARCH) https://nvidia.github.io/nvidia-docker/ubuntu22.04/$(ARCH)
> 
> @elezar Can you tell why the change was done in the first place?

The primary reason for this change is to limit the size of the archive that we're publishing to these repositories through GitHub pages. Since symlinks effectively duplicate the packages, we end up with 3GB archive (which grows with each release) and this gets close to timing out the GitHub pages deployment.

The reason for using ubuntu18.04 as the base repository is that:
1. This existed first since we've been using these repositories for a number of years.
2. The packages are forward-compatible, so these packages work on newer ubuntu versions.
3. Our instructions which download the `.list` files all end up with this repository referenced.

We are in the process of improving the story here and will introduce a generic `.deb` package repository where new packages will be published instead of requiring different repos for all supported platforms.

**Comment by itsthejb** [comment]
I would second that, from a user point of view, the current approach looks like Ubuntu support was dropped

**Comment by PorkCharsui79** [comment]
Please, please, please read the Debian repo guidelines and conform:
https://wiki.debian.org/DebianRepository

**Comment by olariuromeo** [comment]
Err:13 https://nvidia.github.io/libnvidia-container/stable/debian/amd64  Release
  404  Not Found [IP: 185.199.109.153 443]
